//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Series
    {
        public string SeriesInstanceUID { get; set; }
        public string StudyInstanceUID { get; set; }
        public string PatientID { get; set; }
        public Nullable<int> SeriesNumber { get; set; }
        public string SeriesDate { get; set; }
        public string SeriesTime { get; set; }
        public string SeriesDescription { get; set; }
        public string Modality { get; set; }
        public string BodypartExamined { get; set; }
        public int NumberOfSeriesRelatedInstances { get; set; }
        public string SpecificCharacterSet { get; set; }
        public System.DateTime Edited { get; set; }
    }
}
