//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillableItem
    {
        public int UID { get; set; }
        public string Code { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ItemUID { get; set; }
        public int BSMDDUID { get; set; }
        public double Cost { get; set; }
        public Nullable<double> DoctorFee { get; set; }
        public double TotalCost { get; set; }
        public Nullable<int> BillingGroupUID { get; set; }
        public Nullable<int> BillingSubGroupUID { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public string IsEditable { get; set; }
        public string IsPackageItem { get; set; }
        public string IsShareDoctor { get; set; }
        public string ItemNameSearch { get; set; }
        public string Comments { get; set; }
        public string IsDoctorOnly { get; set; }
        public Nullable<int> OrderCategeoryUID { get; set; }
        public Nullable<int> OrderSubCategeoryUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
