//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Careprovider
    {
        public int UID { get; set; }
        public string Code { get; set; }
        public Nullable<int> TITLEUID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SEXXXUID { get; set; }
        public string EnglishName { get; set; }
        public string ImgPath { get; set; }
        public byte[] LicenseImage { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> LicenseIssueDttm { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDttm { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> DOBDttm { get; set; }
        public Nullable<int> CPTYPUID { get; set; }
        public Nullable<bool> IsDoctor { get; set; }
        public Nullable<bool> IsRadiologist { get; set; }
        public Nullable<bool> IsAdminRadiologist { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string LineID { get; set; }
        public Nullable<bool> IsRDUStaff { get; set; }
        public Nullable<bool> IsAdminRadread { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
