//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DischargeEvent
    {
        public long UID { get; set; }
        public long AdmissionEventUID { get; set; }
        public int DSCSTUID { get; set; }
        public Nullable<System.DateTime> MedicalDischargeDttm { get; set; }
        public System.DateTime ActualDischargeDttm { get; set; }
        public int RecordedBy { get; set; }
        public string DischargeComments { get; set; }
        public int MDTRNUID { get; set; }
        public Nullable<int> DSGDSUID { get; set; }
        public int DSCTYUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<int> INFCTUID { get; set; }
        public Nullable<int> AdvicedBy { get; set; }
        public Nullable<System.DateTime> DischargeAdviceDttm { get; set; }
        public Nullable<int> DSHTYPUID { get; set; }
        public Nullable<int> DSOCMUID { get; set; }
        public Nullable<int> CARNSUID { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDttm { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
    }
}
