//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPFillDetail
    {
        public long UID { get; set; }
        public string PatientFillID { get; set; }
        public long IPFillProcessUID { get; set; }
        public long PatientUID { get; set; }
        public Nullable<int> WardUID { get; set; }
        public Nullable<int> BedUID { get; set; }
        public long PatientOrderDetailUID { get; set; }
        public Nullable<int> ItemMasterUID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> IMUOMUID { get; set; }
        public string BatchID { get; set; }
        public System.DateTime ExpiryDttm { get; set; }
        public Nullable<int> StockUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<long> PatientVisitUID { get; set; }
        public Nullable<long> PatientOrderUID { get; set; }
    }
}
