//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemIssue
    {
        public int UID { get; set; }
        public int OrganisationUID { get; set; }
        public Nullable<int> LocationUID { get; set; }
        public int StoreUID { get; set; }
        public Nullable<int> RequestedByLocationUID { get; set; }
        public int RequestedByOrganisationUID { get; set; }
        public int RequestedByStoreUID { get; set; }
        public System.DateTime ItemIssueDttm { get; set; }
        public string ItemIssueID { get; set; }
        public Nullable<int> ISUSTUID { get; set; }
        public Nullable<int> ISSTPUID { get; set; }
        public int IssueBy { get; set; }
        public double NetAmount { get; set; }
        public double OtherCharges { get; set; }
        public string Comments { get; set; }
        public string CancelReason { get; set; }
        public string ItemRequestID { get; set; }
        public Nullable<int> ItemRequestUID { get; set; }
        public string ItemReceiveID { get; set; }
        public Nullable<int> ItemReceiveUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
