//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAverageCost
    {
        public int UID { get; set; }
        public int ItemMasterUID { get; set; }
        public System.DateTime StartDttm { get; set; }
        public Nullable<System.DateTime> EndDttm { get; set; }
        public Nullable<double> InQty { get; set; }
        public double UnitCost { get; set; }
        public double BFQty { get; set; }
        public Nullable<double> BFAvgCost { get; set; }
        public double AvgCost { get; set; }
        public int IMUOMUID { get; set; }
        public string RefNo { get; set; }
        public string RefTable { get; set; }
        public Nullable<int> RefUID { get; set; }
        public string Note { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
