//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int UID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<System.DateTime> LastPasswordModifiredDTTM { get; set; }
        public Nullable<System.DateTime> LastAccessedDTTM { get; set; }
        public Nullable<System.DateTime> LastAccessedWebDttm { get; set; }
        public string HasUserChangedPassword { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public int CareproviderUID { get; set; }
        public System.DateTime CWhen { get; set; }
        public int CUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public int MUser { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
