//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientExamination
    {
        public int UID { get; set; }
        public long PatientUID { get; set; }
        public long PatientVisitUID { get; set; }
        public string Eyes { get; set; }
        public string Ears { get; set; }
        public string Throat { get; set; }
        public string Nose { get; set; }
        public string Teeth { get; set; }
        public string LymphNode { get; set; }
        public string Thyroid { get; set; }
        public string Lung { get; set; }
        public string Heart { get; set; }
        public string Skin { get; set; }
        public string Smoke { get; set; }
        public string Alcohol { get; set; }
        public string DrugAllergy { get; set; }
        public string PersonalHistory { get; set; }
        public string Conclusion { get; set; }
        public Nullable<int> RABSTSUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
