//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTitmus
    {
        public int UID { get; set; }
        public long PatientUID { get; set; }
        public long PatientVisitUID { get; set; }
        public string FarPoint { get; set; }
        public string NearPoint { get; set; }
        public string Depth { get; set; }
        public string Color { get; set; }
        public string Muscle { get; set; }
        public string Visualfield { get; set; }
        public string VARt { get; set; }
        public string VALt { get; set; }
        public string Disease { get; set; }
        public string Conclusion { get; set; }
        public string Recommend { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RABSTSUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
