//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAllergy
    {
        public long UID { get; set; }
        public long PatientUID { get; set; }
        public Nullable<long> PatientVisitUID { get; set; }
        public Nullable<int> ALRCLUID { get; set; }
        public string AllergyDescription { get; set; }
        public Nullable<int> IdentifyingUID { get; set; }
        public string IdentifyingType { get; set; }
        public string AllergicTo { get; set; }
        public Nullable<int> SEVRTUID { get; set; }
        public Nullable<int> CERNTUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
