//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionItem
    {
        public long UID { get; set; }
        public long PrescriptionUID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ROUTEUID { get; set; }
        public Nullable<int> FRQNCUID { get; set; }
        public Nullable<int> DFORMUID { get; set; }
        public string ClinicalComments { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> StartDttm { get; set; }
        public Nullable<int> DrugDuration { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Dosage { get; set; }
        public Nullable<int> PrescriptionUOM { get; set; }
        public string InstructionText { get; set; }
        public string LocalInstructionText { get; set; }
        public Nullable<int> ORDSTUID { get; set; }
        public Nullable<int> PDSTSUID { get; set; }
        public Nullable<int> IMUOMUID { get; set; }
        public Nullable<int> StoreUID { get; set; }
        public Nullable<int> ItemMasterUID { get; set; }
        public int BillableItemUID { get; set; }
        public long PatientOrderDetailUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
