//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int UID { get; set; }
        public int VendorDetailUID { get; set; }
        public string PurchaseOrderID { get; set; }
        public Nullable<System.DateTime> RequiredDttm { get; set; }
        public System.DateTime RequestedDttm { get; set; }
        public Nullable<int> DelieryToStoreUID { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public string Comments { get; set; }
        public int POSTSUID { get; set; }
        public double OtherCharges { get; set; }
        public double NetAmount { get; set; }
        public double Discount { get; set; }
        public string CancelReason { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ApprovalComments { get; set; }
        public string GRNNumber { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
