//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceRelationShip
    {
        public int UID { get; set; }
        public int SourceReferenceValueUID { get; set; }
        public int TargetReferenceValueUID { get; set; }
        public int SourceReferenceDomainUID { get; set; }
        public string SourceReferenceDomainCode { get; set; }
        public int TargetReferenceDomainUID { get; set; }
        public string TargetReferenceDomainCode { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public int MUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int CUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
