//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDetail
    {
        public long UID { get; set; }
        public long RequestUID { get; set; }
        public int RequestitemUID { get; set; }
        public System.DateTime ResultRequiredDttm { get; set; }
        public System.DateTime RequestedDttm { get; set; }
        public string AccessionNumber { get; set; }
        public Nullable<int> RQPRTUID { get; set; }
        public int ORDSTUID { get; set; }
        public Nullable<int> RequestedUserUID { get; set; }
        public string Comments { get; set; }
        public string RequestItemCode { get; set; }
        public string RequestItemName { get; set; }
        public Nullable<int> RIMTYPUID { get; set; }
        public Nullable<int> AssignedByUID { get; set; }
        public Nullable<System.DateTime> AssignedDttm { get; set; }
        public Nullable<int> AssignedToUID { get; set; }
        public Nullable<int> PreparedByUID { get; set; }
        public Nullable<System.DateTime> PreparedDttm { get; set; }
        public Nullable<int> UltrasoundByUID { get; set; }
        public string ProcessingNote { get; set; }
        public string RDUNote { get; set; }
        public Nullable<int> RABSTSUID { get; set; }
        public Nullable<System.DateTime> RDUResultedDttm { get; set; }
        public Nullable<int> RDUStaffUID { get; set; }
        public Nullable<int> RadiologistUID { get; set; }
        public Nullable<long> PatientOrderDetailUID { get; set; }
        public string NetworkPartnerID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
