//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultComponent
    {
        public long UID { get; set; }
        public long ResultUID { get; set; }
        public Nullable<int> ResultItemUID { get; set; }
        public int RVTYPUID { get; set; }
        public string ResultValue { get; set; }
        public string ReferenceRange { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<int> RSUOMUID { get; set; }
        public string Comments { get; set; }
        public string IsAbnormal { get; set; }
        public Nullable<System.DateTime> ResultDTTM { get; set; }
        public string ResultItemName { get; set; }
        public string ResultItemCode { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
