//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specimen
    {
        public int UID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> SPMTPUID { get; set; }
        public Nullable<bool> IsVolumeCollectionReqd { get; set; }
        public Nullable<double> VolumeCollected { get; set; }
        public Nullable<int> VOUNTUID { get; set; }
        public Nullable<System.DateTime> ExpiryDttm { get; set; }
        public Nullable<int> COLSTUID { get; set; }
        public Nullable<int> CLROUUID { get; set; }
        public Nullable<int> COLMDUID { get; set; }
        public string StorageInstuction { get; set; }
        public string HandlingInstruction { get; set; }
        public string Suffix { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
