//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovement
    {
        public long UID { get; set; }
        public int StockUID { get; set; }
        public Nullable<int> StoreUID { get; set; }
        public Nullable<int> ToStoreUID { get; set; }
        public int ItemMasterUID { get; set; }
        public string BatchID { get; set; }
        public Nullable<System.DateTime> StockDttm { get; set; }
        public double TotalBFQty { get; set; }
        public double BFQty { get; set; }
        public double InQty { get; set; }
        public double OutQty { get; set; }
        public double BalQty { get; set; }
        public double TotBalQty { get; set; }
        public int IMUOMUID { get; set; }
        public Nullable<double> UnitCost { get; set; }
        public string RefNo { get; set; }
        public string RefTable { get; set; }
        public Nullable<long> RefUID { get; set; }
        public Nullable<int> RefPatientUID { get; set; }
        public string Note { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public string SerialNumber { get; set; }
    }
}
