//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorDetail
    {
        public int UID { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }
        public int MNFTPUID { get; set; }
        public string MobileNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> ProvinceUID { get; set; }
        public Nullable<int> AmphurUID { get; set; }
        public Nullable<int> DistrictUID { get; set; }
        public string ZipCode { get; set; }
        public string TINNo { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
    }
}
