//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionEvent
    {
        public long UID { get; set; }
        public long PatientVisitUID { get; set; }
        public long PatientUID { get; set; }
        public int CareproviderUID { get; set; }
        public Nullable<int> ExpectedLengthOfStay { get; set; }
        public System.DateTime AdmissionDttm { get; set; }
        public Nullable<System.DateTime> ExpectedDischargeDttm { get; set; }
        public Nullable<int> IPBookingUID { get; set; }
        public Nullable<int> PreviousEventUID { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<System.DateTime> ValidFromDttm { get; set; }
        public Nullable<System.DateTime> ValidToDttm { get; set; }
        public string IsNoVisitorAllowed { get; set; }
        public Nullable<int> RequestingLocationUID { get; set; }
    }
}
