//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEDischargeEvent
    {
        public long UID { get; set; }
        public long PatientAEAdmissionUID { get; set; }
        public System.DateTime CheckOutDttm { get; set; }
        public Nullable<int> DSCCNDUID { get; set; }
        public Nullable<int> DSCTYPUID { get; set; }
        public Nullable<int> DESTINUID { get; set; }
        public Nullable<System.DateTime> DeceasedDttm { get; set; }
        public Nullable<int> ATSTYPUID { get; set; }
        public string DischargeEvents { get; set; }
        public int RecordedBy { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
