//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPackagePrice
    {
        public int UID { get; set; }
        public long BillPackageItemUID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> DoctorShare { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public string StatusFlag { get; set; }
        public long PBLCTUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public int Cuser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int Muser { get; set; }
        public System.DateTime MWhen { get; set; }
    }
}
