//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPackageItem
    {
        public int UID { get; set; }
        public int BillPackageUID { get; set; }
        public int BSMDDUID { get; set; }
        public string Comments { get; set; }
        public int CURNCUID { get; set; }
        public double Amount { get; set; }
        public Nullable<int> BillableItemUID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ItemUID { get; set; }
        public Nullable<int> OrderCategoryUID { get; set; }
        public Nullable<int> OrderSubCategoryUID { get; set; }
        public Nullable<double> DoctorShare { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
