//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int UID { get; set; }
        public long PatientUID { get; set; }
        public int BKSTSUID { get; set; }
        public Nullable<int> PATMSGUID { get; set; }
        public System.DateTime AppointmentDttm { get; set; }
        public Nullable<int> CareProviderUID { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public string StatusFlag { get; set; }
    }
}
