//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckupRuleItem
    {
        public int UID { get; set; }
        public int CheckupRuleUID { get; set; }
        public int ResultItemUID { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Hight { get; set; }
        public string Text { get; set; }
        public string Operator { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
