//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispensedItem
    {
        public long UID { get; set; }
        public long PrescriptionItemUID { get; set; }
        public int StoreUID { get; set; }
        public double Quantity { get; set; }
        public string ItemName { get; set; }
        public int ItemMasterUID { get; set; }
        public Nullable<int> IMUOMUID { get; set; }
        public string BatchID { get; set; }
        public int StockUID { get; set; }
        public Nullable<System.DateTime> ExpiryDttm { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<int> ORDSTUID { get; set; }
        public System.DateTime DispensedDttm { get; set; }
        public Nullable<double> TotalBFQty { get; set; }
        public Nullable<double> BFQty { get; set; }
        public Nullable<long> PatientOrderDetailUID { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public byte[] TIMIESTAMP { get; set; }
    }
}
