//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupReceiptDetail
    {
        public int UID { get; set; }
        public int GroupReceiptUID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> BillableItemUID { get; set; }
        public Nullable<int> OrderSetUID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> PTaxPercentage { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Unit { get; set; }
        public string Comment { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
