//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupReceipt
    {
        public int UID { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public string PayorName { get; set; }
        public int PayorDetailUID { get; set; }
        public string PayorAddress { get; set; }
        public string TINNo { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> NoTaxAmount { get; set; }
        public Nullable<double> BfTaxAmount { get; set; }
        public string Seller { get; set; }
        public string Comment { get; set; }
        public string CancelledReason { get; set; }
        public Nullable<System.DateTime> CancelledDttm { get; set; }
        public Nullable<int> StaffUID { get; set; }
        public Nullable<System.DateTime> StartDttm { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
