//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPBooking
    {
        public int UID { get; set; }
        public long PatientUID { get; set; }
        public int LocationUID { get; set; }
        public Nullable<int> SpecialityUID { get; set; }
        public int CareproviderUID { get; set; }
        public Nullable<int> BedUID { get; set; }
        public System.DateTime AdmissionDttm { get; set; }
        public System.DateTime ExpectedDischargeDttm { get; set; }
        public int ExpectedLengthofStay { get; set; }
        public System.DateTime BookedDttm { get; set; }
        public int BKSTSUID { get; set; }
        public int VISTYUID { get; set; }
        public int BKTYPUID { get; set; }
        public Nullable<int> BDCATUID { get; set; }
        public string ReferredBy { get; set; }
        public Nullable<int> ReferredByUID { get; set; }
        public Nullable<int> RequestedLocationUID { get; set; }
        public Nullable<int> RequestedByUID { get; set; }
        public Nullable<int> CANRSUID { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDttm { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
