//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequest
    {
        public int UID { get; set; }
        public int OrganisationUID { get; set; }
        public Nullable<int> LocationUID { get; set; }
        public int StoreUID { get; set; }
        public Nullable<int> RequestOnLocationUID { get; set; }
        public int RequestOnOrganistaionUID { get; set; }
        public int RequestOnStoreUID { get; set; }
        public Nullable<int> RQSTSUID { get; set; }
        public int RequestedBy { get; set; }
        public Nullable<int> PreferredVendorUID { get; set; }
        public string ItemRequestID { get; set; }
        public System.DateTime RequestedDttm { get; set; }
        public Nullable<int> IRPRIUID { get; set; }
        public string ItemIssueID { get; set; }
        public string Comments { get; set; }
        public string CancelReason { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
