//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int UID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ITMTYPUID { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<int> DrugGenaricUID { get; set; }
        public string GenaricName { get; set; }
        public string GenaricNameSearch { get; set; }
        public string DispenseEnglish { get; set; }
        public string DispenseLocal { get; set; }
        public string OrderInstruction { get; set; }
        public Nullable<int> FRQNCUID { get; set; }
        public Nullable<int> FORMMUID { get; set; }
        public Nullable<int> PDSTSUID { get; set; }
        public Nullable<int> BaseUOM { get; set; }
        public Nullable<int> SalesUOM { get; set; }
        public Nullable<int> PrescriptionUOM { get; set; }
        public Nullable<double> VATPercentage { get; set; }
        public string IsBatchIDMandatory { get; set; }
        public string IsStock { get; set; }
        public string IsNarcotic { get; set; }
        public string CanDispenseWithOutStock { get; set; }
        public Nullable<int> ManufacturerByUID { get; set; }
        public Nullable<int> NRCTPUID { get; set; }
        public Nullable<double> DoseQuantity { get; set; }
        public Nullable<double> MinSalesQty { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<int> ROUTEUID { get; set; }
    }
}
