//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationTransfer
    {
        public long UID { get; set; }
        public long PatientUID { get; set; }
        public long PatientVisitUID { get; set; }
        public int LocationUID { get; set; }
        public Nullable<int> BedUID { get; set; }
        public Nullable<int> BDCATUID { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<System.DateTime> EffectiveDttm { get; set; }
        public Nullable<int> TRNSTUID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> PrimaryBedUID { get; set; }
        public Nullable<int> CANRSUID { get; set; }
        public string CancelComments { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    }
}
