//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MediTechEntities : DbContext
    {
        public MediTechEntities()
            : base("name=MediTechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionEvent> AdmissionEvent { get; set; }
        public virtual DbSet<ADTEventStatus> ADTEventStatus { get; set; }
        public virtual DbSet<AEDischargeEvent> AEDischargeEvent { get; set; }
        public virtual DbSet<AgreementAccountDiscount> AgreementAccountDiscount { get; set; }
        public virtual DbSet<AgreementDetailDiscount> AgreementDetailDiscount { get; set; }
        public virtual DbSet<AgreementItemDiscount> AgreementItemDiscount { get; set; }
        public virtual DbSet<Amphur> Amphur { get; set; }
        public virtual DbSet<AppointmentRequest> AppointmentRequest { get; set; }
        public virtual DbSet<BillableItem> BillableItem { get; set; }
        public virtual DbSet<BillableItemDetail> BillableItemDetail { get; set; }
        public virtual DbSet<BillConfiguration> BillConfiguration { get; set; }
        public virtual DbSet<BillingGroup> BillingGroup { get; set; }
        public virtual DbSet<BillingSubGroup> BillingSubGroup { get; set; }
        public virtual DbSet<BillPackage> BillPackage { get; set; }
        public virtual DbSet<BillPackageItem> BillPackageItem { get; set; }
        public virtual DbSet<BillPackagePrice> BillPackagePrice { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Careprovider> Careprovider { get; set; }
        public virtual DbSet<CareproviderLocation> CareproviderLocation { get; set; }
        public virtual DbSet<CareproviderOrganisation> CareproviderOrganisation { get; set; }
        public virtual DbSet<CareproviderTransfer> CareproviderTransfer { get; set; }
        public virtual DbSet<CCHPI> CCHPI { get; set; }
        public virtual DbSet<CCHPIMaster> CCHPIMaster { get; set; }
        public virtual DbSet<CheckupGroupResult> CheckupGroupResult { get; set; }
        public virtual DbSet<CheckupJobContact> CheckupJobContact { get; set; }
        public virtual DbSet<CheckupJobTask> CheckupJobTask { get; set; }
        public virtual DbSet<CheckupRule> CheckupRule { get; set; }
        public virtual DbSet<CheckupRuleDescription> CheckupRuleDescription { get; set; }
        public virtual DbSet<CheckupRuleItem> CheckupRuleItem { get; set; }
        public virtual DbSet<CheckupRuleRecommend> CheckupRuleRecommend { get; set; }
        public virtual DbSet<CheckupTextMaster> CheckupTextMaster { get; set; }
        public virtual DbSet<ContactAgreementAccount> ContactAgreementAccount { get; set; }
        public virtual DbSet<ContactAgreementAccountDetail> ContactAgreementAccountDetail { get; set; }
        public virtual DbSet<ContactAgreementAccountItem> ContactAgreementAccountItem { get; set; }
        public virtual DbSet<DischargeEvent> DischargeEvent { get; set; }
        public virtual DbSet<DispensedItem> DispensedItem { get; set; }
        public virtual DbSet<DisposeItemList> DisposeItemList { get; set; }
        public virtual DbSet<DisposeStock> DisposeStock { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<DoctorFee> DoctorFee { get; set; }
        public virtual DbSet<DrugGeneric> DrugGeneric { get; set; }
        public virtual DbSet<FavouriteItem> FavouriteItem { get; set; }
        public virtual DbSet<FrequencyDefinition> FrequencyDefinition { get; set; }
        public virtual DbSet<GRNDetail> GRNDetail { get; set; }
        public virtual DbSet<GRNItemList> GRNItemList { get; set; }
        public virtual DbSet<GroupReceipt> GroupReceipt { get; set; }
        public virtual DbSet<GroupReceiptDetail> GroupReceiptDetail { get; set; }
        public virtual DbSet<GroupReceiptPatientBill> GroupReceiptPatientBill { get; set; }
        public virtual DbSet<HealthOrganisation> HealthOrganisation { get; set; }
        public virtual DbSet<HealthOrganisationID> HealthOrganisationID { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompany { get; set; }
        public virtual DbSet<InsurancePlan> InsurancePlan { get; set; }
        public virtual DbSet<IPBooking> IPBooking { get; set; }
        public virtual DbSet<IPFillDetail> IPFillDetail { get; set; }
        public virtual DbSet<IPFillProcess> IPFillProcess { get; set; }
        public virtual DbSet<ItemAverageCost> ItemAverageCost { get; set; }
        public virtual DbSet<ItemIssue> ItemIssue { get; set; }
        public virtual DbSet<ItemIssueDetail> ItemIssueDetail { get; set; }
        public virtual DbSet<ItemMaster> ItemMaster { get; set; }
        public virtual DbSet<ItemReceive> ItemReceive { get; set; }
        public virtual DbSet<ItemReceiveDetail> ItemReceiveDetail { get; set; }
        public virtual DbSet<ItemRequest> ItemRequest { get; set; }
        public virtual DbSet<ItemRequestDetail> ItemRequestDetail { get; set; }
        public virtual DbSet<ItemUOMConversion> ItemUOMConversion { get; set; }
        public virtual DbSet<ItemVendorDetail> ItemVendorDetail { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<LocationTransfer> LocationTransfer { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<MediTechInterface> MediTechInterface { get; set; }
        public virtual DbSet<MediTechInterfaceDetail> MediTechInterfaceDetail { get; set; }
        public virtual DbSet<NotificationTaskResult> NotificationTaskResult { get; set; }
        public virtual DbSet<OrderCategory> OrderCategory { get; set; }
        public virtual DbSet<OrderSet> OrderSet { get; set; }
        public virtual DbSet<OrderSetBillableItem> OrderSetBillableItem { get; set; }
        public virtual DbSet<OrderSubCategory> OrderSubCategory { get; set; }
        public virtual DbSet<PageView> PageView { get; set; }
        public virtual DbSet<PageViewModule> PageViewModule { get; set; }
        public virtual DbSet<PageViewPermission> PageViewPermission { get; set; }
        public virtual DbSet<PastMedicalHistory> PastMedicalHistory { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientAddress> PatientAddress { get; set; }
        public virtual DbSet<PatientAddressMerge> PatientAddressMerge { get; set; }
        public virtual DbSet<PatientADTEvent> PatientADTEvent { get; set; }
        public virtual DbSet<PatientAEAdmission> PatientAEAdmission { get; set; }
        public virtual DbSet<PatientAlert> PatientAlert { get; set; }
        public virtual DbSet<PatientAllergy> PatientAllergy { get; set; }
        public virtual DbSet<PatientAudiogram> PatientAudiogram { get; set; }
        public virtual DbSet<PatientBill> PatientBill { get; set; }
        public virtual DbSet<PatientBillableItem> PatientBillableItem { get; set; }
        public virtual DbSet<PatientBilledItem> PatientBilledItem { get; set; }
        public virtual DbSet<PatientBillEditHistory> PatientBillEditHistory { get; set; }
        public virtual DbSet<PatientConsultation> PatientConsultation { get; set; }
        public virtual DbSet<PatientDeceasedDetail> PatientDeceasedDetail { get; set; }
        public virtual DbSet<PatientDemographicLog> PatientDemographicLog { get; set; }
        public virtual DbSet<PatientEKG> PatientEKG { get; set; }
        public virtual DbSet<PatientExamination> PatientExamination { get; set; }
        public virtual DbSet<PatientFixPrice> PatientFixPrice { get; set; }
        public virtual DbSet<PatientFixPriceHistory> PatientFixPriceHistory { get; set; }
        public virtual DbSet<PatientImage> PatientImage { get; set; }
        public virtual DbSet<PatientInjury> PatientInjury { get; set; }
        public virtual DbSet<PatientInsuranceDetail> PatientInsuranceDetail { get; set; }
        public virtual DbSet<PatientMedicalHistory> PatientMedicalHistory { get; set; }
        public virtual DbSet<PatientMerge> PatientMerge { get; set; }
        public virtual DbSet<PatientMergeDetail> PatientMergeDetail { get; set; }
        public virtual DbSet<PatientMergeEncounter> PatientMergeEncounter { get; set; }
        public virtual DbSet<PatientMuscle> PatientMuscle { get; set; }
        public virtual DbSet<PatientOrder> PatientOrder { get; set; }
        public virtual DbSet<PatientOrderAlert> PatientOrderAlert { get; set; }
        public virtual DbSet<PatientOrderDetail> PatientOrderDetail { get; set; }
        public virtual DbSet<PatientOrderDetailHistory> PatientOrderDetailHistory { get; set; }
        public virtual DbSet<PatientPackage> PatientPackage { get; set; }
        public virtual DbSet<PatientPackageItem> PatientPackageItem { get; set; }
        public virtual DbSet<PatientPaymentDetail> PatientPaymentDetail { get; set; }
        public virtual DbSet<PatientProblem> PatientProblem { get; set; }
        public virtual DbSet<PatientScannedDocument> PatientScannedDocument { get; set; }
        public virtual DbSet<PatientServiceEvent> PatientServiceEvent { get; set; }
        public virtual DbSet<PatientSpirometry> PatientSpirometry { get; set; }
        public virtual DbSet<PatientTitmus> PatientTitmus { get; set; }
        public virtual DbSet<PatientVisit> PatientVisit { get; set; }
        public virtual DbSet<PatientVisitCareProvider> PatientVisitCareProvider { get; set; }
        public virtual DbSet<PatientVisitID> PatientVisitID { get; set; }
        public virtual DbSet<PatientVisitPayor> PatientVisitPayor { get; set; }
        public virtual DbSet<PatientVisualAcuity> PatientVisualAcuity { get; set; }
        public virtual DbSet<PatientVitalSign> PatientVitalSign { get; set; }
        public virtual DbSet<PatientWorkHistory> PatientWorkHistory { get; set; }
        public virtual DbSet<PayorAgreement> PayorAgreement { get; set; }
        public virtual DbSet<PayorAgreement_2> PayorAgreement_2 { get; set; }
        public virtual DbSet<PayorDetail> PayorDetail { get; set; }
        public virtual DbSet<PayorDetail_2> PayorDetail_2 { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<PhysicalExam> PhysicalExam { get; set; }
        public virtual DbSet<PhysicalExamTemplate> PhysicalExamTemplate { get; set; }
        public virtual DbSet<PolicyMaster> PolicyMaster { get; set; }
        public virtual DbSet<PostalCode> PostalCode { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<PrescriptionItem> PrescriptionItem { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
        public virtual DbSet<ProgressNote> ProgressNote { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<PurchaseOrderItemList> PurchaseOrderItemList { get; set; }
        public virtual DbSet<PurchaseOrderPayment> PurchaseOrderPayment { get; set; }
        public virtual DbSet<ReferenceDomain> ReferenceDomain { get; set; }
        public virtual DbSet<ReferenceRelationShip> ReferenceRelationShip { get; set; }
        public virtual DbSet<ReferenceValue> ReferenceValue { get; set; }
        public virtual DbSet<ReportPermission> ReportPermission { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<RequestDetail> RequestDetail { get; set; }
        public virtual DbSet<RequestDetailDocument> RequestDetailDocument { get; set; }
        public virtual DbSet<RequestDetailSpecimen> RequestDetailSpecimen { get; set; }
        public virtual DbSet<RequestItem> RequestItem { get; set; }
        public virtual DbSet<RequestItemGroupResult> RequestItemGroupResult { get; set; }
        public virtual DbSet<RequestItemSpecimen> RequestItemSpecimen { get; set; }
        public virtual DbSet<RequestResultLink> RequestResultLink { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<ResultComponent> ResultComponent { get; set; }
        public virtual DbSet<ResultImage> ResultImage { get; set; }
        public virtual DbSet<ResultItem> ResultItem { get; set; }
        public virtual DbSet<ResultItemRange> ResultItemRange { get; set; }
        public virtual DbSet<ResultRadiology> ResultRadiology { get; set; }
        public virtual DbSet<ResultRadiologyHistory> ResultRadiologyHistory { get; set; }
        public virtual DbSet<ResultRadiologyTemplate> ResultRadiologyTemplate { get; set; }
        public virtual DbSet<ResultTextual> ResultTextual { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleProfile> RoleProfile { get; set; }
        public virtual DbSet<RoleReportPermission> RoleReportPermission { get; set; }
        public virtual DbSet<RoleViewPermission> RoleViewPermission { get; set; }
        public virtual DbSet<SaleReturn> SaleReturn { get; set; }
        public virtual DbSet<SaleReturnList> SaleReturnList { get; set; }
        public virtual DbSet<ScheduleRadiologist> ScheduleRadiologist { get; set; }
        public virtual DbSet<SEQAccessionNumber> SEQAccessionNumber { get; set; }
        public virtual DbSet<SEQCheckupJobNumber> SEQCheckupJobNumber { get; set; }
        public virtual DbSet<SEQConfiguration> SEQConfiguration { get; set; }
        public virtual DbSet<SEQDISPOSEID> SEQDISPOSEID { get; set; }
        public virtual DbSet<SEQERVisitID> SEQERVisitID { get; set; }
        public virtual DbSet<SEQFILLDETAILID> SEQFILLDETAILID { get; set; }
        public virtual DbSet<SEQGRNID> SEQGRNID { get; set; }
        public virtual DbSet<SEQGroupReceipt> SEQGroupReceipt { get; set; }
        public virtual DbSet<SEQIPDVisitID> SEQIPDVisitID { get; set; }
        public virtual DbSet<SEQIPFILLID> SEQIPFILLID { get; set; }
        public virtual DbSet<SEQITCODE> SEQITCODE { get; set; }
        public virtual DbSet<SEQItemIssue> SEQItemIssue { get; set; }
        public virtual DbSet<SEQItemReceive> SEQItemReceive { get; set; }
        public virtual DbSet<SEQItemRequest> SEQItemRequest { get; set; }
        public virtual DbSet<SEQLISRequest> SEQLISRequest { get; set; }
        public virtual DbSet<SEQPatientBill> SEQPatientBill { get; set; }
        public virtual DbSet<SEQPatientID> SEQPatientID { get; set; }
        public virtual DbSet<SEQPatientINVBill> SEQPatientINVBill { get; set; }
        public virtual DbSet<SEQPatientOrder> SEQPatientOrder { get; set; }
        public virtual DbSet<SEQPrescription> SEQPrescription { get; set; }
        public virtual DbSet<SEQPROID> SEQPROID { get; set; }
        public virtual DbSet<SEQResult> SEQResult { get; set; }
        public virtual DbSet<SEQRISRequest> SEQRISRequest { get; set; }
        public virtual DbSet<SEQSaleReturn> SEQSaleReturn { get; set; }
        public virtual DbSet<SEQSTAID> SEQSTAID { get; set; }
        public virtual DbSet<SEQTestCodeID> SEQTestCodeID { get; set; }
        public virtual DbSet<SEQVisitID> SEQVisitID { get; set; }
        public virtual DbSet<SessionDefinition> SessionDefinition { get; set; }
        public virtual DbSet<SessionWithdrawnDetail> SessionWithdrawnDetail { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Specimen> Specimen { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockAdjustment> StockAdjustment { get; set; }
        public virtual DbSet<StockBalance> StockBalance { get; set; }
        public virtual DbSet<StockMovement> StockMovement { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<StoreUOMConversion> StoreUOMConversion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VendorDetail> VendorDetail { get; set; }
        public virtual DbSet<VIPPatient> VIPPatient { get; set; }
        public virtual DbSet<WellnessData> WellnessData { get; set; }
        public virtual DbSet<XrayTranslateCondition> XrayTranslateCondition { get; set; }
        public virtual DbSet<XrayTranslateConditionDetail> XrayTranslateConditionDetail { get; set; }
        public virtual DbSet<XrayTranslateMapping> XrayTranslateMapping { get; set; }
        public virtual DbSet<vAllBillableItemRates> vAllBillableItemRates { get; set; }
        public virtual DbSet<vAllPayorAgreements> vAllPayorAgreements { get; set; }
        public virtual DbSet<vAllPayorAgreementsDiscount> vAllPayorAgreementsDiscount { get; set; }
    
        [DbFunction("MediTechEntities", "fGetBigIntList")]
        public virtual IQueryable<fGetBigIntList_Result> fGetBigIntList(string p_KeyWordList)
        {
            var p_KeyWordListParameter = p_KeyWordList != null ?
                new ObjectParameter("P_KeyWordList", p_KeyWordList) :
                new ObjectParameter("P_KeyWordList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetBigIntList_Result>("[MediTechEntities].[fGetBigIntList](@P_KeyWordList)", p_KeyWordListParameter);
        }
    
        [DbFunction("MediTechEntities", "fGetPackagePriceROOMCharge")]
        public virtual IQueryable<fGetPackagePriceROOMCharge_Result> fGetPackagePriceROOMCharge(Nullable<int> patientBillableITemUID, Nullable<System.DateTime> dateOrder, Nullable<int> billPackageITEMUID, Nullable<int> tariff)
        {
            var patientBillableITemUIDParameter = patientBillableITemUID.HasValue ?
                new ObjectParameter("PatientBillableITemUID", patientBillableITemUID) :
                new ObjectParameter("PatientBillableITemUID", typeof(int));
    
            var dateOrderParameter = dateOrder.HasValue ?
                new ObjectParameter("DateOrder", dateOrder) :
                new ObjectParameter("DateOrder", typeof(System.DateTime));
    
            var billPackageITEMUIDParameter = billPackageITEMUID.HasValue ?
                new ObjectParameter("BillPackageITEMUID", billPackageITEMUID) :
                new ObjectParameter("BillPackageITEMUID", typeof(int));
    
            var tariffParameter = tariff.HasValue ?
                new ObjectParameter("Tariff", tariff) :
                new ObjectParameter("Tariff", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetPackagePriceROOMCharge_Result>("[MediTechEntities].[fGetPackagePriceROOMCharge](@PatientBillableITemUID, @DateOrder, @BillPackageITEMUID, @Tariff)", patientBillableITemUIDParameter, dateOrderParameter, billPackageITEMUIDParameter, tariffParameter);
        }
    
        [DbFunction("MediTechEntities", "splitstring")]
        public virtual IQueryable<splitstring_Result> splitstring(string stringToSplit)
        {
            var stringToSplitParameter = stringToSplit != null ?
                new ObjectParameter("stringToSplit", stringToSplit) :
                new ObjectParameter("stringToSplit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<splitstring_Result>("[MediTechEntities].[splitstring](@stringToSplit)", stringToSplitParameter);
        }
    
        [DbFunction("MediTechEntities", "fGetRoomAdjust")]
        public virtual IQueryable<fGetRoomAdjust_Result> fGetRoomAdjust(Nullable<System.DateTime> dateOrder, Nullable<int> tariff, Nullable<int> refRoomcharge)
        {
            var dateOrderParameter = dateOrder.HasValue ?
                new ObjectParameter("DateOrder", dateOrder) :
                new ObjectParameter("DateOrder", typeof(System.DateTime));
    
            var tariffParameter = tariff.HasValue ?
                new ObjectParameter("Tariff", tariff) :
                new ObjectParameter("Tariff", typeof(int));
    
            var refRoomchargeParameter = refRoomcharge.HasValue ?
                new ObjectParameter("RefRoomcharge", refRoomcharge) :
                new ObjectParameter("RefRoomcharge", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetRoomAdjust_Result>("[MediTechEntities].[fGetRoomAdjust](@DateOrder, @Tariff, @RefRoomcharge)", dateOrderParameter, tariffParameter, refRoomchargeParameter);
        }
    
        public virtual ObjectResult<pCheckOrderDuplicate_Result> pCheckOrderDuplicate(Nullable<long> p_PatientUID, Nullable<long> p_PatientVisitUID, Nullable<int> p_BillableItemUID)
        {
            var p_PatientUIDParameter = p_PatientUID.HasValue ?
                new ObjectParameter("P_PatientUID", p_PatientUID) :
                new ObjectParameter("P_PatientUID", typeof(long));
    
            var p_PatientVisitUIDParameter = p_PatientVisitUID.HasValue ?
                new ObjectParameter("P_PatientVisitUID", p_PatientVisitUID) :
                new ObjectParameter("P_PatientVisitUID", typeof(long));
    
            var p_BillableItemUIDParameter = p_BillableItemUID.HasValue ?
                new ObjectParameter("P_BillableItemUID", p_BillableItemUID) :
                new ObjectParameter("P_BillableItemUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pCheckOrderDuplicate_Result>("pCheckOrderDuplicate", p_PatientUIDParameter, p_PatientVisitUIDParameter, p_BillableItemUIDParameter);
        }
    
        public virtual ObjectResult<pGetCheckupRiskAudioTimus_Result> pGetCheckupRiskAudioTimus(Nullable<long> p_PatientUID, Nullable<long> p_PayorDetailUID)
        {
            var p_PatientUIDParameter = p_PatientUID.HasValue ?
                new ObjectParameter("P_PatientUID", p_PatientUID) :
                new ObjectParameter("P_PatientUID", typeof(long));
    
            var p_PayorDetailUIDParameter = p_PayorDetailUID.HasValue ?
                new ObjectParameter("P_PayorDetailUID", p_PayorDetailUID) :
                new ObjectParameter("P_PayorDetailUID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetCheckupRiskAudioTimus_Result>("pGetCheckupRiskAudioTimus", p_PatientUIDParameter, p_PayorDetailUIDParameter);
        }
    
        public virtual int pInvenClearItemReceiveDetail(Nullable<int> p_ItemReceiveUID, Nullable<int> p_UserUID)
        {
            var p_ItemReceiveUIDParameter = p_ItemReceiveUID.HasValue ?
                new ObjectParameter("P_ItemReceiveUID", p_ItemReceiveUID) :
                new ObjectParameter("P_ItemReceiveUID", typeof(int));
    
            var p_UserUIDParameter = p_UserUID.HasValue ?
                new ObjectParameter("P_UserUID", p_UserUID) :
                new ObjectParameter("P_UserUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pInvenClearItemReceiveDetail", p_ItemReceiveUIDParameter, p_UserUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> pInvenTransferItemEcount(Nullable<int> p_ItemIssueUID, Nullable<int> p_UserUID)
        {
            var p_ItemIssueUIDParameter = p_ItemIssueUID.HasValue ?
                new ObjectParameter("P_ItemIssueUID", p_ItemIssueUID) :
                new ObjectParameter("P_ItemIssueUID", typeof(int));
    
            var p_UserUIDParameter = p_UserUID.HasValue ?
                new ObjectParameter("P_UserUID", p_UserUID) :
                new ObjectParameter("P_UserUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("pInvenTransferItemEcount", p_ItemIssueUIDParameter, p_UserUIDParameter);
        }
    
        public virtual ObjectResult<pRPTEcoutSumGroupReceipt_Result> pRPTEcoutSumGroupReceipt(Nullable<System.DateTime> p_DateFrom, Nullable<System.DateTime> p_DateTo, string p_OrganisationList, Nullable<int> p_VisitTypeUID)
        {
            var p_DateFromParameter = p_DateFrom.HasValue ?
                new ObjectParameter("P_DateFrom", p_DateFrom) :
                new ObjectParameter("P_DateFrom", typeof(System.DateTime));
    
            var p_DateToParameter = p_DateTo.HasValue ?
                new ObjectParameter("P_DateTo", p_DateTo) :
                new ObjectParameter("P_DateTo", typeof(System.DateTime));
    
            var p_OrganisationListParameter = p_OrganisationList != null ?
                new ObjectParameter("P_OrganisationList", p_OrganisationList) :
                new ObjectParameter("P_OrganisationList", typeof(string));
    
            var p_VisitTypeUIDParameter = p_VisitTypeUID.HasValue ?
                new ObjectParameter("P_VisitTypeUID", p_VisitTypeUID) :
                new ObjectParameter("P_VisitTypeUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pRPTEcoutSumGroupReceipt_Result>("pRPTEcoutSumGroupReceipt", p_DateFromParameter, p_DateToParameter, p_OrganisationListParameter, p_VisitTypeUIDParameter);
        }
    
        public virtual int pSearchItemMasterCriteria(string p_Text)
        {
            var p_TextParameter = p_Text != null ?
                new ObjectParameter("P_Text", p_Text) :
                new ObjectParameter("P_Text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pSearchItemMasterCriteria", p_TextParameter);
        }
    
        public virtual ObjectResult<pSearchListDispensedItemForReturn_Result> pSearchListDispensedItemForReturn(Nullable<int> p_PatientVisitUid, Nullable<int> p_StoreUID, string p_PrescriptionNumber, string p_ItemName)
        {
            var p_PatientVisitUidParameter = p_PatientVisitUid.HasValue ?
                new ObjectParameter("P_PatientVisitUid", p_PatientVisitUid) :
                new ObjectParameter("P_PatientVisitUid", typeof(int));
    
            var p_StoreUIDParameter = p_StoreUID.HasValue ?
                new ObjectParameter("P_StoreUID", p_StoreUID) :
                new ObjectParameter("P_StoreUID", typeof(int));
    
            var p_PrescriptionNumberParameter = p_PrescriptionNumber != null ?
                new ObjectParameter("P_PrescriptionNumber", p_PrescriptionNumber) :
                new ObjectParameter("P_PrescriptionNumber", typeof(string));
    
            var p_ItemNameParameter = p_ItemName != null ?
                new ObjectParameter("P_ItemName", p_ItemName) :
                new ObjectParameter("P_ItemName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pSearchListDispensedItemForReturn_Result>("pSearchListDispensedItemForReturn", p_PatientVisitUidParameter, p_StoreUIDParameter, p_PrescriptionNumberParameter, p_ItemNameParameter);
        }
    
        public virtual ObjectResult<pSearchUnbilledPatientsForCheckup_Result> pSearchUnbilledPatientsForCheckup(Nullable<long> p_PatientUID, Nullable<System.DateTime> p_BillFromDTTM, Nullable<System.DateTime> p_BillToDTTM, Nullable<int> p_InsuranceCompanyUID, Nullable<int> p_CheckupjobUID, Nullable<int> p_OwnerOrganisationUID)
        {
            var p_PatientUIDParameter = p_PatientUID.HasValue ?
                new ObjectParameter("P_PatientUID", p_PatientUID) :
                new ObjectParameter("P_PatientUID", typeof(long));
    
            var p_BillFromDTTMParameter = p_BillFromDTTM.HasValue ?
                new ObjectParameter("P_BillFromDTTM", p_BillFromDTTM) :
                new ObjectParameter("P_BillFromDTTM", typeof(System.DateTime));
    
            var p_BillToDTTMParameter = p_BillToDTTM.HasValue ?
                new ObjectParameter("P_BillToDTTM", p_BillToDTTM) :
                new ObjectParameter("P_BillToDTTM", typeof(System.DateTime));
    
            var p_InsuranceCompanyUIDParameter = p_InsuranceCompanyUID.HasValue ?
                new ObjectParameter("P_InsuranceCompanyUID", p_InsuranceCompanyUID) :
                new ObjectParameter("P_InsuranceCompanyUID", typeof(int));
    
            var p_CheckupjobUIDParameter = p_CheckupjobUID.HasValue ?
                new ObjectParameter("P_CheckupjobUID", p_CheckupjobUID) :
                new ObjectParameter("P_CheckupjobUID", typeof(int));
    
            var p_OwnerOrganisationUIDParameter = p_OwnerOrganisationUID.HasValue ?
                new ObjectParameter("P_OwnerOrganisationUID", p_OwnerOrganisationUID) :
                new ObjectParameter("P_OwnerOrganisationUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pSearchUnbilledPatientsForCheckup_Result>("pSearchUnbilledPatientsForCheckup", p_PatientUIDParameter, p_BillFromDTTMParameter, p_BillToDTTMParameter, p_InsuranceCompanyUIDParameter, p_CheckupjobUIDParameter, p_OwnerOrganisationUIDParameter);
        }
    
        public virtual ObjectResult<pGetWardView_Result> pGetWardView(Nullable<int> p_ParentLocationUID)
        {
            var p_ParentLocationUIDParameter = p_ParentLocationUID.HasValue ?
                new ObjectParameter("P_ParentLocationUID", p_ParentLocationUID) :
                new ObjectParameter("P_ParentLocationUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetWardView_Result>("pGetWardView", p_ParentLocationUIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
