//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MediTechEntities : DbContext
    {
        public MediTechEntities()
            : base("name=MediTechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionEvent> AdmissionEvent { get; set; }
        public virtual DbSet<ADTEventStatus> ADTEventStatus { get; set; }
        public virtual DbSet<AEDischargeEvent> AEDischargeEvent { get; set; }
        public virtual DbSet<AgreementAccountDiscount> AgreementAccountDiscount { get; set; }
        public virtual DbSet<AgreementDetailDiscount> AgreementDetailDiscount { get; set; }
        public virtual DbSet<AgreementItemDiscount> AgreementItemDiscount { get; set; }
        public virtual DbSet<Amphur> Amphur { get; set; }
        public virtual DbSet<AppointmentRequest> AppointmentRequest { get; set; }
        public virtual DbSet<BillableItem> BillableItem { get; set; }
        public virtual DbSet<BillableItemDetail> BillableItemDetail { get; set; }
        public virtual DbSet<BillConfiguration> BillConfiguration { get; set; }
        public virtual DbSet<BillingGroup> BillingGroup { get; set; }
        public virtual DbSet<BillingSubGroup> BillingSubGroup { get; set; }
        public virtual DbSet<BillPackage> BillPackage { get; set; }
        public virtual DbSet<BillPackageItem> BillPackageItem { get; set; }
        public virtual DbSet<BillPackagePrice> BillPackagePrice { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Careprovider> Careprovider { get; set; }
        public virtual DbSet<CareproviderLocation> CareproviderLocation { get; set; }
        public virtual DbSet<CareproviderOrganisation> CareproviderOrganisation { get; set; }
        public virtual DbSet<CareproviderTransfer> CareproviderTransfer { get; set; }
        public virtual DbSet<CCHPI> CCHPI { get; set; }
        public virtual DbSet<CCHPIMaster> CCHPIMaster { get; set; }
        public virtual DbSet<CheckupGroupResult> CheckupGroupResult { get; set; }
        public virtual DbSet<CheckupJobContact> CheckupJobContact { get; set; }
        public virtual DbSet<CheckupJobTask> CheckupJobTask { get; set; }
        public virtual DbSet<CheckupRule> CheckupRule { get; set; }
        public virtual DbSet<CheckupRuleDescription> CheckupRuleDescription { get; set; }
        public virtual DbSet<CheckupRuleItem> CheckupRuleItem { get; set; }
        public virtual DbSet<CheckupRuleRecommend> CheckupRuleRecommend { get; set; }
        public virtual DbSet<CheckupTextMaster> CheckupTextMaster { get; set; }
        public virtual DbSet<ContactAgreementAccount> ContactAgreementAccount { get; set; }
        public virtual DbSet<ContactAgreementAccountDetail> ContactAgreementAccountDetail { get; set; }
        public virtual DbSet<ContactAgreementAccountItem> ContactAgreementAccountItem { get; set; }
        public virtual DbSet<DischargeEvent> DischargeEvent { get; set; }
        public virtual DbSet<DispensedItem> DispensedItem { get; set; }
        public virtual DbSet<DisposeItemList> DisposeItemList { get; set; }
        public virtual DbSet<DisposeStock> DisposeStock { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<DoctorFee> DoctorFee { get; set; }
        public virtual DbSet<DrugGeneric> DrugGeneric { get; set; }
        public virtual DbSet<FavouriteItem> FavouriteItem { get; set; }
        public virtual DbSet<FrequencyDefinition> FrequencyDefinition { get; set; }
        public virtual DbSet<GRNDetail> GRNDetail { get; set; }
        public virtual DbSet<GRNItemList> GRNItemList { get; set; }
        public virtual DbSet<GroupReceipt> GroupReceipt { get; set; }
        public virtual DbSet<GroupReceiptDetail> GroupReceiptDetail { get; set; }
        public virtual DbSet<GroupReceiptPatientBill> GroupReceiptPatientBill { get; set; }
        public virtual DbSet<HealthOrganisation> HealthOrganisation { get; set; }
        public virtual DbSet<HealthOrganisationID> HealthOrganisationID { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompany { get; set; }
        public virtual DbSet<InsurancePlan> InsurancePlan { get; set; }
        public virtual DbSet<IPBooking> IPBooking { get; set; }
        public virtual DbSet<IPFillDetail> IPFillDetail { get; set; }
        public virtual DbSet<IPFillProcess> IPFillProcess { get; set; }
        public virtual DbSet<ItemAverageCost> ItemAverageCost { get; set; }
        public virtual DbSet<ItemIssue> ItemIssue { get; set; }
        public virtual DbSet<ItemIssueDetail> ItemIssueDetail { get; set; }
        public virtual DbSet<ItemMaster> ItemMaster { get; set; }
        public virtual DbSet<ItemReceive> ItemReceive { get; set; }
        public virtual DbSet<ItemReceiveDetail> ItemReceiveDetail { get; set; }
        public virtual DbSet<ItemRequest> ItemRequest { get; set; }
        public virtual DbSet<ItemRequestDetail> ItemRequestDetail { get; set; }
        public virtual DbSet<ItemUOMConversion> ItemUOMConversion { get; set; }
        public virtual DbSet<ItemVendorDetail> ItemVendorDetail { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<LocationTransfer> LocationTransfer { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<MediTechInterface> MediTechInterface { get; set; }
        public virtual DbSet<MediTechInterfaceDetail> MediTechInterfaceDetail { get; set; }
        public virtual DbSet<meditechtestpatchInterface> meditechtestpatchInterface { get; set; }
        public virtual DbSet<meditechtestpatchInterfaceDetail> meditechtestpatchInterfaceDetail { get; set; }
        public virtual DbSet<NotificationTaskResult> NotificationTaskResult { get; set; }
        public virtual DbSet<OrderCategory> OrderCategory { get; set; }
        public virtual DbSet<OrderSet> OrderSet { get; set; }
        public virtual DbSet<OrderSetBillableItem> OrderSetBillableItem { get; set; }
        public virtual DbSet<OrderSubCategory> OrderSubCategory { get; set; }
        public virtual DbSet<PageView> PageView { get; set; }
        public virtual DbSet<PageViewModule> PageViewModule { get; set; }
        public virtual DbSet<PageViewPermission> PageViewPermission { get; set; }
        public virtual DbSet<PastMedicalHistory> PastMedicalHistory { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientAddress> PatientAddress { get; set; }
        public virtual DbSet<PatientAddressMerge> PatientAddressMerge { get; set; }
        public virtual DbSet<PatientADTEvent> PatientADTEvent { get; set; }
        public virtual DbSet<PatientAEAdmission> PatientAEAdmission { get; set; }
        public virtual DbSet<PatientAllergy> PatientAllergy { get; set; }
        public virtual DbSet<PatientAudiogram> PatientAudiogram { get; set; }
        public virtual DbSet<PatientBill> PatientBill { get; set; }
        public virtual DbSet<PatientBillableItem> PatientBillableItem { get; set; }
        public virtual DbSet<PatientBilledItem> PatientBilledItem { get; set; }
        public virtual DbSet<PatientBillEditHistory> PatientBillEditHistory { get; set; }
        public virtual DbSet<PatientConsultation> PatientConsultation { get; set; }
        public virtual DbSet<PatientDeceasedDetail> PatientDeceasedDetail { get; set; }
        public virtual DbSet<PatientDemographicLog> PatientDemographicLog { get; set; }
        public virtual DbSet<PatientEKG> PatientEKG { get; set; }
        public virtual DbSet<PatientExamination> PatientExamination { get; set; }
        public virtual DbSet<PatientFixPrice> PatientFixPrice { get; set; }
        public virtual DbSet<PatientFixPriceHistory> PatientFixPriceHistory { get; set; }
        public virtual DbSet<PatientImage> PatientImage { get; set; }
        public virtual DbSet<PatientInjury> PatientInjury { get; set; }
        public virtual DbSet<PatientInsuranceDetail> PatientInsuranceDetail { get; set; }
        public virtual DbSet<PatientMedicalHistory> PatientMedicalHistory { get; set; }
        public virtual DbSet<PatientMerge> PatientMerge { get; set; }
        public virtual DbSet<PatientMergeDetail> PatientMergeDetail { get; set; }
        public virtual DbSet<PatientMergeEncounter> PatientMergeEncounter { get; set; }
        public virtual DbSet<PatientMuscle> PatientMuscle { get; set; }
        public virtual DbSet<PatientOrder> PatientOrder { get; set; }
        public virtual DbSet<PatientOrderAlert> PatientOrderAlert { get; set; }
        public virtual DbSet<PatientOrderDetail> PatientOrderDetail { get; set; }
        public virtual DbSet<PatientOrderDetailHistory> PatientOrderDetailHistory { get; set; }
        public virtual DbSet<PatientPackage> PatientPackage { get; set; }
        public virtual DbSet<PatientPackageItem> PatientPackageItem { get; set; }
        public virtual DbSet<PatientPaymentDetail> PatientPaymentDetail { get; set; }
        public virtual DbSet<PatientProblem> PatientProblem { get; set; }
        public virtual DbSet<PatientScannedDocument> PatientScannedDocument { get; set; }
        public virtual DbSet<PatientServiceEvent> PatientServiceEvent { get; set; }
        public virtual DbSet<PatientSpirometry> PatientSpirometry { get; set; }
        public virtual DbSet<PatientTitmus> PatientTitmus { get; set; }
        public virtual DbSet<PatientVisit> PatientVisit { get; set; }
        public virtual DbSet<PatientVisitCareProvider> PatientVisitCareProvider { get; set; }
        public virtual DbSet<PatientVisitID> PatientVisitID { get; set; }
        public virtual DbSet<PatientVisitPayor> PatientVisitPayor { get; set; }
        public virtual DbSet<PatientVisualAcuity> PatientVisualAcuity { get; set; }
        public virtual DbSet<PatientVitalSign> PatientVitalSign { get; set; }
        public virtual DbSet<PatientWorkHistory> PatientWorkHistory { get; set; }
        public virtual DbSet<PayorAgreement> PayorAgreement { get; set; }
        public virtual DbSet<PayorAgreement_2> PayorAgreement_2 { get; set; }
        public virtual DbSet<PayorDetail> PayorDetail { get; set; }
        public virtual DbSet<PayorDetail_2> PayorDetail_2 { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<PhysicalExam> PhysicalExam { get; set; }
        public virtual DbSet<PhysicalExamTemplate> PhysicalExamTemplate { get; set; }
        public virtual DbSet<PolicyMaster> PolicyMaster { get; set; }
        public virtual DbSet<PostalCode> PostalCode { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<PrescriptionItem> PrescriptionItem { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
        public virtual DbSet<ProgressNote> ProgressNote { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<PurchaseOrderItemList> PurchaseOrderItemList { get; set; }
        public virtual DbSet<PurchaseOrderPayment> PurchaseOrderPayment { get; set; }
        public virtual DbSet<ReferenceDomain> ReferenceDomain { get; set; }
        public virtual DbSet<ReferenceRelationShip> ReferenceRelationShip { get; set; }
        public virtual DbSet<ReferenceValue> ReferenceValue { get; set; }
        public virtual DbSet<ReportPermission> ReportPermission { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<RequestDetail> RequestDetail { get; set; }
        public virtual DbSet<RequestDetailDocument> RequestDetailDocument { get; set; }
        public virtual DbSet<RequestDetailSpecimen> RequestDetailSpecimen { get; set; }
        public virtual DbSet<RequestItem> RequestItem { get; set; }
        public virtual DbSet<RequestItemGroupResult> RequestItemGroupResult { get; set; }
        public virtual DbSet<RequestItemSpecimen> RequestItemSpecimen { get; set; }
        public virtual DbSet<RequestResultLink> RequestResultLink { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<ResultComponent> ResultComponent { get; set; }
        public virtual DbSet<ResultImage> ResultImage { get; set; }
        public virtual DbSet<ResultItem> ResultItem { get; set; }
        public virtual DbSet<ResultItemRange> ResultItemRange { get; set; }
        public virtual DbSet<ResultRadiology> ResultRadiology { get; set; }
        public virtual DbSet<ResultRadiologyHistory> ResultRadiologyHistory { get; set; }
        public virtual DbSet<ResultRadiologyTemplate> ResultRadiologyTemplate { get; set; }
        public virtual DbSet<ResultTextual> ResultTextual { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleProfile> RoleProfile { get; set; }
        public virtual DbSet<RoleReportPermission> RoleReportPermission { get; set; }
        public virtual DbSet<RoleViewPermission> RoleViewPermission { get; set; }
        public virtual DbSet<SaleReturn> SaleReturn { get; set; }
        public virtual DbSet<SaleReturnList> SaleReturnList { get; set; }
        public virtual DbSet<ScheduleRadiologist> ScheduleRadiologist { get; set; }
        public virtual DbSet<SEQAccessionNumber> SEQAccessionNumber { get; set; }
        public virtual DbSet<SEQCheckupJobNumber> SEQCheckupJobNumber { get; set; }
        public virtual DbSet<SEQConfiguration> SEQConfiguration { get; set; }
        public virtual DbSet<SEQDISPOSEID> SEQDISPOSEID { get; set; }
        public virtual DbSet<SEQERVisitID> SEQERVisitID { get; set; }
        public virtual DbSet<SEQFILLDETAILID> SEQFILLDETAILID { get; set; }
        public virtual DbSet<SEQGRNID> SEQGRNID { get; set; }
        public virtual DbSet<SEQGroupReceipt> SEQGroupReceipt { get; set; }
        public virtual DbSet<SEQIPDVisitID> SEQIPDVisitID { get; set; }
        public virtual DbSet<SEQIPFILLID> SEQIPFILLID { get; set; }
        public virtual DbSet<SEQITCODE> SEQITCODE { get; set; }
        public virtual DbSet<SEQItemIssue> SEQItemIssue { get; set; }
        public virtual DbSet<SEQItemReceive> SEQItemReceive { get; set; }
        public virtual DbSet<SEQItemRequest> SEQItemRequest { get; set; }
        public virtual DbSet<SEQLISRequest> SEQLISRequest { get; set; }
        public virtual DbSet<SEQPatientBill> SEQPatientBill { get; set; }
        public virtual DbSet<SEQPatientID> SEQPatientID { get; set; }
        public virtual DbSet<SEQPatientINVBill> SEQPatientINVBill { get; set; }
        public virtual DbSet<SEQPatientOrder> SEQPatientOrder { get; set; }
        public virtual DbSet<SEQPrescription> SEQPrescription { get; set; }
        public virtual DbSet<SEQPROID> SEQPROID { get; set; }
        public virtual DbSet<SEQResult> SEQResult { get; set; }
        public virtual DbSet<SEQRISRequest> SEQRISRequest { get; set; }
        public virtual DbSet<SEQSTAID> SEQSTAID { get; set; }
        public virtual DbSet<SEQTestCodeID> SEQTestCodeID { get; set; }
        public virtual DbSet<SEQVisitID> SEQVisitID { get; set; }
        public virtual DbSet<SessionDefinition> SessionDefinition { get; set; }
        public virtual DbSet<SessionWithdrawnDetail> SessionWithdrawnDetail { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Specimen> Specimen { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockAdjustment> StockAdjustment { get; set; }
        public virtual DbSet<StockBalance> StockBalance { get; set; }
        public virtual DbSet<StockMovement> StockMovement { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<StoreUOMConversion> StoreUOMConversion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VendorDetail> VendorDetail { get; set; }
        public virtual DbSet<VIPPatient> VIPPatient { get; set; }
        public virtual DbSet<WellnessData> WellnessData { get; set; }
        public virtual DbSet<XrayTranslateCondition> XrayTranslateCondition { get; set; }
        public virtual DbSet<XrayTranslateConditionDetail> XrayTranslateConditionDetail { get; set; }
        public virtual DbSet<XrayTranslateMapping> XrayTranslateMapping { get; set; }
        public virtual DbSet<vAllBillableItemRates> vAllBillableItemRates { get; set; }
        public virtual DbSet<vAllPayorAgreements> vAllPayorAgreements { get; set; }
        public virtual DbSet<vAllPayorAgreementsDiscount> vAllPayorAgreementsDiscount { get; set; }
    
        [DbFunction("Entities", "fGetBigIntList")]
        public virtual IQueryable<fGetBigIntList_Result> fGetBigIntList(string p_KeyWordList)
        {
            var p_KeyWordListParameter = p_KeyWordList != null ?
                new ObjectParameter("P_KeyWordList", p_KeyWordList) :
                new ObjectParameter("P_KeyWordList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetBigIntList_Result>("[Entities].[fGetBigIntList](@P_KeyWordList)", p_KeyWordListParameter);
        }
    
        [DbFunction("Entities", "fGetPackagePriceROOMCharge")]
        public virtual IQueryable<fGetPackagePriceROOMCharge_Result> fGetPackagePriceROOMCharge(Nullable<int> patientBillableITemUID, Nullable<System.DateTime> dateOrder, Nullable<int> billPackageITEMUID, Nullable<int> tariff)
        {
            var patientBillableITemUIDParameter = patientBillableITemUID.HasValue ?
                new ObjectParameter("PatientBillableITemUID", patientBillableITemUID) :
                new ObjectParameter("PatientBillableITemUID", typeof(int));
    
            var dateOrderParameter = dateOrder.HasValue ?
                new ObjectParameter("DateOrder", dateOrder) :
                new ObjectParameter("DateOrder", typeof(System.DateTime));
    
            var billPackageITEMUIDParameter = billPackageITEMUID.HasValue ?
                new ObjectParameter("BillPackageITEMUID", billPackageITEMUID) :
                new ObjectParameter("BillPackageITEMUID", typeof(int));
    
            var tariffParameter = tariff.HasValue ?
                new ObjectParameter("Tariff", tariff) :
                new ObjectParameter("Tariff", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetPackagePriceROOMCharge_Result>("[Entities].[fGetPackagePriceROOMCharge](@PatientBillableITemUID, @DateOrder, @BillPackageITEMUID, @Tariff)", patientBillableITemUIDParameter, dateOrderParameter, billPackageITEMUIDParameter, tariffParameter);
        }
    
        [DbFunction("Entities", "splitstring")]
        public virtual IQueryable<splitstring_Result> splitstring(string stringToSplit)
        {
            var stringToSplitParameter = stringToSplit != null ?
                new ObjectParameter("stringToSplit", stringToSplit) :
                new ObjectParameter("stringToSplit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<splitstring_Result>("[Entities].[splitstring](@stringToSplit)", stringToSplitParameter);
        }
    
        public virtual ObjectResult<string> pCheckPatientBillStatus(Nullable<long> p_PatientUID, Nullable<long> p_PatientVisitUID)
        {
            var p_PatientUIDParameter = p_PatientUID.HasValue ?
                new ObjectParameter("P_PatientUID", p_PatientUID) :
                new ObjectParameter("P_PatientUID", typeof(long));
    
            var p_PatientVisitUIDParameter = p_PatientVisitUID.HasValue ?
                new ObjectParameter("P_PatientVisitUID", p_PatientVisitUID) :
                new ObjectParameter("P_PatientVisitUID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pCheckPatientBillStatus", p_PatientUIDParameter, p_PatientVisitUIDParameter);
        }
    
        public virtual ObjectResult<pGetPatientBillableItemsAccount_Result> pGetPatientBillableItemsAccount(Nullable<long> p_PatientUID, Nullable<long> p_PatientVisitUID, Nullable<int> p_PackageUID, Nullable<long> p_PatientVisitPayorUID, Nullable<System.DateTime> p_FromDttm, Nullable<System.DateTime> p_ToDttm, Nullable<int> p_AccountUID, Nullable<int> p_SubAccountUID, Nullable<int> p_LocationUID)
        {
            var p_PatientUIDParameter = p_PatientUID.HasValue ?
                new ObjectParameter("P_PatientUID", p_PatientUID) :
                new ObjectParameter("P_PatientUID", typeof(long));
    
            var p_PatientVisitUIDParameter = p_PatientVisitUID.HasValue ?
                new ObjectParameter("P_PatientVisitUID", p_PatientVisitUID) :
                new ObjectParameter("P_PatientVisitUID", typeof(long));
    
            var p_PackageUIDParameter = p_PackageUID.HasValue ?
                new ObjectParameter("P_PackageUID", p_PackageUID) :
                new ObjectParameter("P_PackageUID", typeof(int));
    
            var p_PatientVisitPayorUIDParameter = p_PatientVisitPayorUID.HasValue ?
                new ObjectParameter("P_PatientVisitPayorUID", p_PatientVisitPayorUID) :
                new ObjectParameter("P_PatientVisitPayorUID", typeof(long));
    
            var p_FromDttmParameter = p_FromDttm.HasValue ?
                new ObjectParameter("P_FromDttm", p_FromDttm) :
                new ObjectParameter("P_FromDttm", typeof(System.DateTime));
    
            var p_ToDttmParameter = p_ToDttm.HasValue ?
                new ObjectParameter("P_ToDttm", p_ToDttm) :
                new ObjectParameter("P_ToDttm", typeof(System.DateTime));
    
            var p_AccountUIDParameter = p_AccountUID.HasValue ?
                new ObjectParameter("P_AccountUID", p_AccountUID) :
                new ObjectParameter("P_AccountUID", typeof(int));
    
            var p_SubAccountUIDParameter = p_SubAccountUID.HasValue ?
                new ObjectParameter("P_SubAccountUID", p_SubAccountUID) :
                new ObjectParameter("P_SubAccountUID", typeof(int));
    
            var p_LocationUIDParameter = p_LocationUID.HasValue ?
                new ObjectParameter("P_LocationUID", p_LocationUID) :
                new ObjectParameter("P_LocationUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetPatientBillableItemsAccount_Result>("pGetPatientBillableItemsAccount", p_PatientUIDParameter, p_PatientVisitUIDParameter, p_PackageUIDParameter, p_PatientVisitPayorUIDParameter, p_FromDttmParameter, p_ToDttmParameter, p_AccountUIDParameter, p_SubAccountUIDParameter, p_LocationUIDParameter);
        }
    
        public virtual ObjectResult<pGetPatientBillableItemsBySA_Result> pGetPatientBillableItemsBySA(Nullable<long> p_PatientUID, Nullable<long> p_PatientVisitUID, Nullable<int> p_AccountUID, Nullable<int> p_SubAccountUID, Nullable<long> p_PatientVisitPayorUID, Nullable<int> p_CareProviderUID, Nullable<int> p_BillableItemUID, Nullable<System.DateTime> p_FromDttm, Nullable<System.DateTime> p_ToDttm, string p_IsPackage, Nullable<int> p_LocationUID)
        {
            var p_PatientUIDParameter = p_PatientUID.HasValue ?
                new ObjectParameter("P_PatientUID", p_PatientUID) :
                new ObjectParameter("P_PatientUID", typeof(long));
    
            var p_PatientVisitUIDParameter = p_PatientVisitUID.HasValue ?
                new ObjectParameter("P_PatientVisitUID", p_PatientVisitUID) :
                new ObjectParameter("P_PatientVisitUID", typeof(long));
    
            var p_AccountUIDParameter = p_AccountUID.HasValue ?
                new ObjectParameter("P_AccountUID", p_AccountUID) :
                new ObjectParameter("P_AccountUID", typeof(int));
    
            var p_SubAccountUIDParameter = p_SubAccountUID.HasValue ?
                new ObjectParameter("P_SubAccountUID", p_SubAccountUID) :
                new ObjectParameter("P_SubAccountUID", typeof(int));
    
            var p_PatientVisitPayorUIDParameter = p_PatientVisitPayorUID.HasValue ?
                new ObjectParameter("P_PatientVisitPayorUID", p_PatientVisitPayorUID) :
                new ObjectParameter("P_PatientVisitPayorUID", typeof(long));
    
            var p_CareProviderUIDParameter = p_CareProviderUID.HasValue ?
                new ObjectParameter("P_CareProviderUID", p_CareProviderUID) :
                new ObjectParameter("P_CareProviderUID", typeof(int));
    
            var p_BillableItemUIDParameter = p_BillableItemUID.HasValue ?
                new ObjectParameter("P_BillableItemUID", p_BillableItemUID) :
                new ObjectParameter("P_BillableItemUID", typeof(int));
    
            var p_FromDttmParameter = p_FromDttm.HasValue ?
                new ObjectParameter("P_FromDttm", p_FromDttm) :
                new ObjectParameter("P_FromDttm", typeof(System.DateTime));
    
            var p_ToDttmParameter = p_ToDttm.HasValue ?
                new ObjectParameter("P_ToDttm", p_ToDttm) :
                new ObjectParameter("P_ToDttm", typeof(System.DateTime));
    
            var p_IsPackageParameter = p_IsPackage != null ?
                new ObjectParameter("P_IsPackage", p_IsPackage) :
                new ObjectParameter("P_IsPackage", typeof(string));
    
            var p_LocationUIDParameter = p_LocationUID.HasValue ?
                new ObjectParameter("P_LocationUID", p_LocationUID) :
                new ObjectParameter("P_LocationUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetPatientBillableItemsBySA_Result>("pGetPatientBillableItemsBySA", p_PatientUIDParameter, p_PatientVisitUIDParameter, p_AccountUIDParameter, p_SubAccountUIDParameter, p_PatientVisitPayorUIDParameter, p_CareProviderUIDParameter, p_BillableItemUIDParameter, p_FromDttmParameter, p_ToDttmParameter, p_IsPackageParameter, p_LocationUIDParameter);
        }
    
        public virtual ObjectResult<pGetPatientBillableItemsSubAccount_Result> pGetPatientBillableItemsSubAccount(Nullable<long> p_PatientUID, Nullable<long> p_PatientVisitUID, Nullable<int> p_PackageUID, Nullable<long> p_PatientVisitPayorUID, Nullable<System.DateTime> p_FromDttm, Nullable<System.DateTime> p_ToDttm, string p_IsPackage, Nullable<int> p_AccountUID, Nullable<int> p_SubAccountUID, Nullable<int> p_LocationUID)
        {
            var p_PatientUIDParameter = p_PatientUID.HasValue ?
                new ObjectParameter("P_PatientUID", p_PatientUID) :
                new ObjectParameter("P_PatientUID", typeof(long));
    
            var p_PatientVisitUIDParameter = p_PatientVisitUID.HasValue ?
                new ObjectParameter("P_PatientVisitUID", p_PatientVisitUID) :
                new ObjectParameter("P_PatientVisitUID", typeof(long));
    
            var p_PackageUIDParameter = p_PackageUID.HasValue ?
                new ObjectParameter("P_PackageUID", p_PackageUID) :
                new ObjectParameter("P_PackageUID", typeof(int));
    
            var p_PatientVisitPayorUIDParameter = p_PatientVisitPayorUID.HasValue ?
                new ObjectParameter("P_PatientVisitPayorUID", p_PatientVisitPayorUID) :
                new ObjectParameter("P_PatientVisitPayorUID", typeof(long));
    
            var p_FromDttmParameter = p_FromDttm.HasValue ?
                new ObjectParameter("P_FromDttm", p_FromDttm) :
                new ObjectParameter("P_FromDttm", typeof(System.DateTime));
    
            var p_ToDttmParameter = p_ToDttm.HasValue ?
                new ObjectParameter("P_ToDttm", p_ToDttm) :
                new ObjectParameter("P_ToDttm", typeof(System.DateTime));
    
            var p_IsPackageParameter = p_IsPackage != null ?
                new ObjectParameter("P_IsPackage", p_IsPackage) :
                new ObjectParameter("P_IsPackage", typeof(string));
    
            var p_AccountUIDParameter = p_AccountUID.HasValue ?
                new ObjectParameter("P_AccountUID", p_AccountUID) :
                new ObjectParameter("P_AccountUID", typeof(int));
    
            var p_SubAccountUIDParameter = p_SubAccountUID.HasValue ?
                new ObjectParameter("P_SubAccountUID", p_SubAccountUID) :
                new ObjectParameter("P_SubAccountUID", typeof(int));
    
            var p_LocationUIDParameter = p_LocationUID.HasValue ?
                new ObjectParameter("P_LocationUID", p_LocationUID) :
                new ObjectParameter("P_LocationUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetPatientBillableItemsSubAccount_Result>("pGetPatientBillableItemsSubAccount", p_PatientUIDParameter, p_PatientVisitUIDParameter, p_PackageUIDParameter, p_PatientVisitPayorUIDParameter, p_FromDttmParameter, p_ToDttmParameter, p_IsPackageParameter, p_AccountUIDParameter, p_SubAccountUIDParameter, p_LocationUIDParameter);
        }
    
        public virtual ObjectResult<string> pMergeBillRecipet(Nullable<int> patientVisitUID, Nullable<int> sourcePatientVisitPayorUID, Nullable<int> desPatientVisitPayorUID, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var patientVisitUIDParameter = patientVisitUID.HasValue ?
                new ObjectParameter("PatientVisitUID", patientVisitUID) :
                new ObjectParameter("PatientVisitUID", typeof(int));
    
            var sourcePatientVisitPayorUIDParameter = sourcePatientVisitPayorUID.HasValue ?
                new ObjectParameter("SourcePatientVisitPayorUID", sourcePatientVisitPayorUID) :
                new ObjectParameter("SourcePatientVisitPayorUID", typeof(int));
    
            var desPatientVisitPayorUIDParameter = desPatientVisitPayorUID.HasValue ?
                new ObjectParameter("DesPatientVisitPayorUID", desPatientVisitPayorUID) :
                new ObjectParameter("DesPatientVisitPayorUID", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pMergeBillRecipet", patientVisitUIDParameter, sourcePatientVisitPayorUIDParameter, desPatientVisitPayorUIDParameter, dateFromParameter, dateToParameter);
        }
    }
}
