//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTaskResult
    {
        public long UID { get; set; }
        public long ResultUID { get; set; }
        public string NetworkPartnerID { get; set; }
        public System.DateTime ResultEnteredDttm { get; set; }
        public System.DateTime CWhen { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public string OwnerOrganisationCode { get; set; }
        public int Status { get; set; }
    }
}
