//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSetBillableItem
    {
        public int UID { get; set; }
        public int BillableItemUID { get; set; }
        public int OrderSetUID { get; set; }
        public string OrderCatalogName { get; set; }
        public Nullable<int> FRQNCUID { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> DoseQty { get; set; }
        public string ProcessingNotes { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> DoctorFee { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
