//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientBillableItem
    {
        public long UID { get; set; }
        public long PatientUID { get; set; }
        public Nullable<long> PatientVisitUID { get; set; }
        public long IdentifyingUID { get; set; }
        public string IdentifyingType { get; set; }
        public Nullable<int> ProcedureUID { get; set; }
        public int BSMDDUID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public string Description { get; set; }
        public Nullable<int> BillableItemUID { get; set; }
        public string Comments { get; set; }
        public Nullable<double> ItemMultiplier { get; set; }
        public Nullable<System.DateTime> StartDttm { get; set; }
        public Nullable<System.DateTime> EndDttm { get; set; }
        public Nullable<int> DiscountAuthorizedBy { get; set; }
        public Nullable<int> ItemUID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> VISITYUID { get; set; }
        public Nullable<int> RSLVLUID { get; set; }
        public Nullable<int> CareProviderUID { get; set; }
        public Nullable<double> ConsultantShare { get; set; }
        public Nullable<double> EducationCess { get; set; }
        public Nullable<double> HigherEducationCess { get; set; }
        public Nullable<double> ServiceTax { get; set; }
        public Nullable<System.DateTime> EventOccuredDttm { get; set; }
        public Nullable<int> QNUOMUID { get; set; }
        public Nullable<double> ConsultantDiscount { get; set; }
        public Nullable<long> PatientVisitPayorUID { get; set; }
        public Nullable<int> PayorDetailUID { get; set; }
        public string BatchID { get; set; }
        public Nullable<double> VATPercentage { get; set; }
        public Nullable<double> InternalCost { get; set; }
        public string CalculateTaxOnMRP { get; set; }
        public Nullable<int> StoreUID { get; set; }
        public Nullable<int> BillPackageUID { get; set; }
        public Nullable<double> SplitDiscount { get; set; }
        public Nullable<int> BLTYPUID { get; set; }
        public string OrderType { get; set; }
        public Nullable<long> OrderTypeUID { get; set; }
        public string ReceiptNumber { get; set; }
        public string RefundBillNumber { get; set; }
        public Nullable<long> PatientOrderDetailUID { get; set; }
        public Nullable<long> IPFillProcessUID { get; set; }
        public Nullable<int> ORDSTUID { get; set; }
        public string IsModified { get; set; }
        public Nullable<long> PreviousVisitUID { get; set; }
        public Nullable<int> ENTYPUID { get; set; }
        public Nullable<long> AllocatedPatBillableItemUID { get; set; }
        public Nullable<System.DateTime> ExpiryDttm { get; set; }
        public Nullable<int> GroupUID { get; set; }
        public Nullable<int> SubGroupUID { get; set; }
        public Nullable<double> GroupMaxCoverage { get; set; }
        public Nullable<double> GroupCovered { get; set; }
        public Nullable<double> SubGroupMaxCoverage { get; set; }
        public Nullable<double> SubGroupCovered { get; set; }
        public Nullable<double> ItemMaxCoverage { get; set; }
        public Nullable<double> ItemCovered { get; set; }
        public Nullable<int> PatientFixPriceUID { get; set; }
        public Nullable<int> PBLCTUID { get; set; }
        public Nullable<int> ALLDIUID { get; set; }
        public Nullable<int> OrderSetBillableItemUID { get; set; }
        public Nullable<int> OrderSetUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
