//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedicalHistory
    {
        public int UID { get; set; }
        public long PatientUID { get; set; }
        public string PastMedical { get; set; }
        public Nullable<System.DateTime> PastMedicalDttm { get; set; }
        public string ChronicDisease { get; set; }
        public string SurgicalDetail { get; set; }
        public string ImmunizationDetail { get; set; }
        public string Familyhistory { get; set; }
        public string LongTemMedication { get; set; }
        public string AllergyDescription { get; set; }
        public string Smoke { get; set; }
        public string SmokePeriodYear { get; set; }
        public string SmokePeriodMonth { get; set; }
        public string BFQuitSmoke { get; set; }
        public string Alcohol { get; set; }
        public string AlcohoPeriodYear { get; set; }
        public string AlcohoPeriodMonth { get; set; }
        public string Narcotic { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
