//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        public long UID { get; set; }
        public long PatientUID { get; set; }
        public Nullable<int> ENTYPUID { get; set; }
        public Nullable<int> CareProviderUID { get; set; }
        public Nullable<int> VISTSUID { get; set; }
        public Nullable<int> VISTYUID { get; set; }
        public Nullable<int> PRITYUID { get; set; }
        public Nullable<int> PBLCTUID { get; set; }
        public Nullable<System.DateTime> StartDttm { get; set; }
        public Nullable<System.DateTime> EndDttm { get; set; }
        public Nullable<System.DateTime> ArrivedDttm { get; set; }
        public Nullable<int> LocationUID { get; set; }
        public string VisitID { get; set; }
        public string IsBillFinalized { get; set; }
        public Nullable<int> ENSTAUID { get; set; }
        public Nullable<int> VisitLocationUID { get; set; }
        public Nullable<int> CurrentCareProviderUID { get; set; }
        public Nullable<int> IPBookingUID { get; set; }
        public Nullable<int> BookingUID { get; set; }
        public Nullable<int> CheckupJobUID { get; set; }
        public Nullable<int> BedUID { get; set; }
        public string IsReAdmisstion { get; set; }
        public string CompanyName { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RefNo { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
