//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVitalSign
    {
        public int UID { get; set; }
        public long PatientUID { get; set; }
        public long PatientVisitUID { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> RespiratoryRate { get; set; }
        public Nullable<double> Temprature { get; set; }
        public Nullable<double> Pulse { get; set; }
        public Nullable<System.DateTime> RecordedDttm { get; set; }
        public Nullable<double> BMIValue { get; set; }
        public Nullable<double> BSAValue { get; set; }
        public Nullable<double> BPSys { get; set; }
        public Nullable<double> BPDio { get; set; }
        public System.DateTime CWhen { get; set; }
        public int CUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public int MUser { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
