//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInjury
    {
        public int UID { get; set; }
        public long PatientUID { get; set; }
        public Nullable<System.DateTime> OccuredDate { get; set; }
        public string BodyLocation { get; set; }
        public string InjuryDetail { get; set; }
        public Nullable<int> INRYSEVUID { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public Nullable<System.DateTime> CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
