//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAEAdmission
    {
        public long UID { get; set; }
        public long PatientVisitUID { get; set; }
        public long PatientUID { get; set; }
        public int ARRMDUID { get; set; }
        public Nullable<int> ESCTPUID { get; set; }
        public string EscortName { get; set; }
        public Nullable<int> RELTNUID { get; set; }
        public string ContactNumber { get; set; }
        public string VehicleNumber { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<int> MLCREAUID { get; set; }
        public Nullable<System.DateTime> EmergencyOcurredDttm { get; set; }
        public Nullable<int> EMGTPUID { get; set; }
        public Nullable<int> EMGCDUID { get; set; }
        public Nullable<int> ProblemUID { get; set; }
        public string InjuryReason { get; set; }
        public string EmergencyExamDetail { get; set; }
        public string IsDead { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string Line4 { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> AmphurUID { get; set; }
        public Nullable<int> ProvinceUID { get; set; }
        public Nullable<int> DistrictUID { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
    }
}
