//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientBilledItem
    {
        public long UID { get; set; }
        public long PatientBillUID { get; set; }
        public Nullable<System.DateTime> EventOccuredDttm { get; set; }
        public string ServiceName { get; set; }
        public int BillableItemUID { get; set; }
        public string ItemName { get; set; }
        public double ItemMultiplier { get; set; }
        public Nullable<int> BillingGroupUID { get; set; }
        public Nullable<int> BillingSubGroupUID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<int> CareproviderUID { get; set; }
        public Nullable<double> DoctorFee { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<double> ExtendCost { get; set; }
        public Nullable<long> PatientBillableItemUID { get; set; }
        public long PatientOrderDetailUID { get; set; }
        public Nullable<long> PatientPackageItemUID { get; set; }
        public Nullable<int> BillPackageUID { get; set; }
        public Nullable<double> PackageItemAmount { get; set; }
        public Nullable<int> StoreUID { get; set; }
        public Nullable<int> StockUID { get; set; }
        public string BatchID { get; set; }
        public int BSMDDUID { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
