//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMerge
    {
        public int UID { get; set; }
        public Nullable<int> MergedByUID { get; set; }
        public Nullable<System.DateTime> MergedDttm { get; set; }
        public long MajorPatientUID { get; set; }
        public long MinorPatientUID { get; set; }
        public string IsUnMerge { get; set; }
        public Nullable<int> MRGTPUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
