//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitCareProvider
    {
        public long UID { get; set; }
        public long PatientVisitUID { get; set; }
        public Nullable<int> CareproviderUID { get; set; }
        public Nullable<System.DateTime> StartDttm { get; set; }
        public Nullable<System.DateTime> SeenDttm { get; set; }
        public string CareProviderName { get; set; }
        public Nullable<int> LocationUID { get; set; }
        public Nullable<int> ReferralUID { get; set; }
        public Nullable<int> PACLSUID { get; set; }
        public Nullable<int> BookingUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
