//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPaymentDetail
    {
        public long UID { get; set; }
        public Nullable<long> PatientBillUID { get; set; }
        public Nullable<long> PatientUID { get; set; }
        public Nullable<long> PatientVisitUID { get; set; }
        public int PAYMDUID { get; set; }
        public Nullable<int> CURNCUID { get; set; }
        public System.DateTime PaidDttm { get; set; }
        public double Amount { get; set; }
        public Nullable<int> CRDTYUID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> CardExpiryDttm { get; set; }
        public string RecieptNumber { get; set; }
        public Nullable<long> PatientEpisodePackageUID { get; set; }
        public Nullable<int> ADVTPUID { get; set; }
        public string BankName { get; set; }
        public string AuthorizationNumber { get; set; }
        public string IsRefund { get; set; }
        public string RefundReceiptNumber { get; set; }
        public Nullable<double> ForeignCurrencyAmt { get; set; }
        public Nullable<double> ConversionRate { get; set; }
        public Nullable<double> TDSAmount { get; set; }
        public Nullable<double> WriteOff { get; set; }
        public Nullable<double> ExcessAmount { get; set; }
        public Nullable<int> BLCATUID { get; set; }
        public string Comments { get; set; }
        public string IsAdvance { get; set; }
        public Nullable<double> SpecialAmount { get; set; }
        public string IsCautiousAdvance { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
