//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientProblem
    {
        public long UID { get; set; }
        public long PatientUID { get; set; }
        public long PatientVisitUID { get; set; }
        public int ProblemUID { get; set; }
        public string ProblemCode { get; set; }
        public string ProblemName { get; set; }
        public string ProblemDescription { get; set; }
        public System.DateTime RecordedDttm { get; set; }
        public int RecordedBy { get; set; }
        public string IsPrimary { get; set; }
        public string IsUnderline { get; set; }
        public Nullable<System.DateTime> OnsetDttm { get; set; }
        public Nullable<System.DateTime> ClosureDttm { get; set; }
        public string ClosureComments { get; set; }
        public Nullable<int> SEVRTUID { get; set; }
        public Nullable<int> PBMTYUID { get; set; }
        public Nullable<int> DIAGTYPUID { get; set; }
        public Nullable<int> CERNTUID { get; set; }
        public Nullable<int> BDLOCUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
