//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisualAcuity
    {
        public int UID { get; set; }
        public int PatientUID { get; set; }
        public int PatientVisitUID { get; set; }
        public string AstigmaticRight { get; set; }
        public string AstigmaticLeft { get; set; }
        public string MyopiaRight { get; set; }
        public string MyopiaLeft { get; set; }
        public string HyperopiaRight { get; set; }
        public string HyperopiaLeft { get; set; }
        public string ViewRight { get; set; }
        public string ViewLeft { get; set; }
        public string VARight { get; set; }
        public string VALeft { get; set; }
        public string BlindColor { get; set; }
        public string Disease { get; set; }
        public string ViewResult { get; set; }
        public string Recommend { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RABSTSUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
