//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long UID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public Nullable<int> SEXXXUID { get; set; }
        public Nullable<int> TITLEUID { get; set; }
        public string PatientID { get; set; }
        public string PatientID2 { get; set; }
        public Nullable<System.DateTime> DOBDttm { get; set; }
        public bool DOBComputed { get; set; }
        public Nullable<int> BLOODUID { get; set; }
        public Nullable<bool> IsVIP { get; set; }
        public string IDCard { get; set; }
        public Nullable<int> RELGNUID { get; set; }
        public string IDLine { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> NATNLUID { get; set; }
        public string IDPassport { get; set; }
        public Nullable<int> MARRYUID { get; set; }
        public Nullable<int> OCCUPUID { get; set; }
        public string SecondPhone { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> LastVisitDttm { get; set; }
        public string DeathStatus { get; set; }
        public Nullable<System.DateTime> DeathDttm { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
