//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInsuranceDetail
    {
        public long UID { get; set; }
        public long PatientUID { get; set; }
        public Nullable<long> PatientVisitUID { get; set; }
        public int InsuranceCompanyUID { get; set; }
        public string PolicyNumber { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> StartDttm { get; set; }
        public Nullable<System.DateTime> EndDttm { get; set; }
        public Nullable<double> EligibleAmount { get; set; }
        public string InsuranceCompanyName { get; set; }
        public string PolicyName { get; set; }
        public Nullable<int> PayorDetailUID { get; set; }
        public string CCNNumber { get; set; }
        public Nullable<int> PolicyMasterUID { get; set; }
        public Nullable<int> PayorAgreementUID { get; set; }
        public Nullable<int> PAYRTPUID { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
