//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientBill
    {
        public long UID { get; set; }
        public Nullable<long> PatientUID { get; set; }
        public Nullable<long> PatientVisitUID { get; set; }
        public Nullable<System.DateTime> BillGeneratedDttm { get; set; }
        public Nullable<double> AdvanceAmount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public string BillNumber { get; set; }
        public Nullable<int> PBLCTUID { get; set; }
        public Nullable<int> BLTYPUID { get; set; }
        public string IsPaymentComplete { get; set; }
        public string IsRefund { get; set; }
        public double PaidAmount { get; set; }
        public Nullable<double> ChangeAmount { get; set; }
        public string ReferredBy { get; set; }
        public Nullable<int> StaffUID { get; set; }
        public Nullable<int> PAYMDUID { get; set; }
        public Nullable<int> SALTOUID { get; set; }
        public string IdentifyingType { get; set; }
        public string PatientName { get; set; }
        public Nullable<long> PatientVisitPayorUID { get; set; }
        public Nullable<int> PayorDetailUID { get; set; }
        public Nullable<int> PayorAgreementUID { get; set; }
        public string CancelReason { get; set; }
        public Nullable<System.DateTime> CancelledDttm { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
