//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDeceasedDetail
    {
        public long UID { get; set; }
        public Nullable<long> PatientVisitUID { get; set; }
        public long PatientUID { get; set; }
        public System.DateTime DeathDttm { get; set; }
        public Nullable<System.DateTime> DeathTime { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<int> DCSRNUID { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public string IsConfirmed { get; set; }
        public string PatientMessage { get; set; }
        public Nullable<int> ATPSTYUID { get; set; }
    }
}
