//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAddressMerge
    {
        public int UID { get; set; }
        public int PatientMergeUID { get; set; }
        public int IdentifyingUID { get; set; }
        public string IdentifyingType { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public Nullable<int> ADTYPUID { get; set; }
        public Nullable<int> DistrictUID { get; set; }
        public Nullable<int> AmphurUID { get; set; }
        public Nullable<int> ProvinceUID { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> SEXXXUID { get; set; }
        public Nullable<int> BLOODUID { get; set; }
        public byte[] ImageContent { get; set; }
        public string MobilePhone { get; set; }
        public string SecondPhone { get; set; }
        public string Comments { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
