//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAudiogram
    {
        public int UID { get; set; }
        public long PatientUID { get; set; }
        public long PatientVisitUID { get; set; }
        public string R500Hz { get; set; }
        public string R1000Hz { get; set; }
        public string R2000Hz { get; set; }
        public string R3000Hz { get; set; }
        public string R4000Hz { get; set; }
        public string R6000Hz { get; set; }
        public string R8000Hz { get; set; }
        public string L500Hz { get; set; }
        public string L1000Hz { get; set; }
        public string L2000Hz { get; set; }
        public string L3000Hz { get; set; }
        public string L4000Hz { get; set; }
        public string L6000Hz { get; set; }
        public string L8000Hz { get; set; }
        public string AudioRightResult { get; set; }
        public string AudioLeftResult { get; set; }
        public string Recommend { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RABSTSUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
