//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientOrderDetail
    {
        public long UID { get; set; }
        public long PatientOrderUID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<long> IdentifyingUID { get; set; }
        public string IdentifyingType { get; set; }
        public Nullable<System.DateTime> StartDttm { get; set; }
        public Nullable<System.DateTime> EndDttm { get; set; }
        public int ORDSTUID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> QNUOMUID { get; set; }
        public Nullable<int> FRQNCUID { get; set; }
        public string Comments { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> DoctorFee { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public string IsPriceOverwrite { get; set; }
        public Nullable<double> OverwritePrice { get; set; }
        public Nullable<double> OriginalUnitPrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> ROUTEUID { get; set; }
        public Nullable<int> DFORMUID { get; set; }
        public Nullable<int> PDSTSUID { get; set; }
        public Nullable<double> UsedQuantity { get; set; }
        public Nullable<double> Dosage { get; set; }
        public Nullable<int> DrugDuration { get; set; }
        public string InstructionText { get; set; }
        public string LocalInstructionText { get; set; }
        public int BillableItemUID { get; set; }
        public Nullable<int> StoreUID { get; set; }
        public string MainFixPrice { get; set; }
        public Nullable<int> PatientFixPriceUID { get; set; }
        public Nullable<long> ParentUID { get; set; }
        public string IsStandingOrder { get; set; }
        public Nullable<int> BillPackageUID { get; set; }
        public Nullable<int> CareproviderUID { get; set; }
        public string CancelledReason { get; set; }
        public Nullable<int> CancelledByUserUID { get; set; }
        public Nullable<System.DateTime> CancelledDttm { get; set; }
        public Nullable<long> PatientPackageUID { get; set; }
        public string IsStockItem { get; set; }
        public Nullable<int> PatientVisitPayorUID { get; set; }
        public Nullable<int> PayorDetailUID { get; set; }
        public Nullable<int> PatientPackageItemUID { get; set; }
        public Nullable<int> OrderSetUID { get; set; }
        public Nullable<int> OrderSetBillableItemUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
