//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayorDetail
    {
        public int UID { get; set; }
        public string Code { get; set; }
        public string PayorName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> DistrictUID { get; set; }
        public Nullable<int> AmphurUID { get; set; }
        public Nullable<int> ProvinceUID { get; set; }
        public string ZipCode { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> PYRACATUID { get; set; }
        public string ContactPersonName { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> CRDTRMUID { get; set; }
        public Nullable<int> PBLCTUID { get; set; }
        public Nullable<int> InsuranceCompanyUID { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public string Note { get; set; }
        public string GovernmentNo { get; set; }
        public Nullable<int> OldPayorDetailUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
