//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long UID { get; set; }
        public long PatientVisitUID { get; set; }
        public long PatientUID { get; set; }
        public int RequestedUserUID { get; set; }
        public System.DateTime RequestedDttm { get; set; }
        public string RequestNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RQPRTUID { get; set; }
        public Nullable<int> BSMDDUID { get; set; }
        public Nullable<int> ORDSTUID { get; set; }
        public Nullable<long> PatientOrderUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
