//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDetailSpecimen
    {
        public long UID { get; set; }
        public long RequestDetailUID { get; set; }
        public int SpecimenUID { get; set; }
        public string SpecimenName { get; set; }
        public int SPMTPUID { get; set; }
        public int ContainerUID { get; set; }
        public Nullable<double> VolumeCollected { get; set; }
        public Nullable<int> VOUNTUID { get; set; }
        public Nullable<System.DateTime> CollectionDttm { get; set; }
        public Nullable<int> COLSTUID { get; set; }
        public Nullable<int> CLROUUID { get; set; }
        public Nullable<int> COLMDUID { get; set; }
        public Nullable<int> CollectedBy { get; set; }
        public string Comments { get; set; }
        public string StorageInstuction { get; set; }
        public string HandlingInstruction { get; set; }
        public Nullable<int> SPSTSUID { get; set; }
        public string ReviewComments { get; set; }
        public string SpecimenNumber { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
