//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultRadiologyTemplate
    {
        public int UID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public string PlainText { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<int> SEXXXUID { get; set; }
        public Nullable<int> RIMTYPUID { get; set; }
        public Nullable<int> RABSTSUID { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
    }
}
