//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEQConfiguration
    {
        public int UID { get; set; }
        public string SEQName { get; set; }
        public string SEQTableName { get; set; }
        public string SEQPrefix { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public string ReseedInterval { get; set; }
        public Nullable<System.DateTime> LastReseedDttm { get; set; }
        public string IDFormat { get; set; }
        public Nullable<int> IDLength { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
    }
}
