//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int UID { get; set; }
        public int StoreUID { get; set; }
        public int ItemMasterUID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> VendorDetailUID { get; set; }
        public Nullable<int> ManufacturerUID { get; set; }
        public double Quantity { get; set; }
        public int IMUOMUID { get; set; }
        public string BatchID { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public string IsExpired { get; set; }
        public Nullable<System.DateTime> ExpiryDttm { get; set; }
        public string Comments { get; set; }
        public Nullable<int> DSPSTUID { get; set; }
        public string DisposeComments { get; set; }
        public Nullable<int> GRNDetailUID { get; set; }
        public Nullable<System.DateTime> GRNDttm { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
