//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment
    {
        public int UID { get; set; }
        public int StoreUID { get; set; }
        public int StockUID { get; set; }
        public int ItemMasterUID { get; set; }
        public string ItemName { get; set; }
        public string BatchID { get; set; }
        public double ActualQuantity { get; set; }
        public int ActualUOM { get; set; }
        public double QuantityAdjusted { get; set; }
        public double AdjustedQuantity { get; set; }
        public int AdjustedUOM { get; set; }
        public string StockAdjustmentID { get; set; }
        public string Comments { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int CUser { get; set; }
        public System.DateTime CWhen { get; set; }
        public int MUser { get; set; }
        public System.DateTime MWhen { get; set; }
        public string StatusFlag { get; set; }
        public int OwnerOrganisationUID { get; set; }
        public byte[] TIMESTAMP { get; set; }
    }
}
