//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAllPayorAgreements
    {
        public int Polyuid { get; set; }
        public int AgreementUID { get; set; }
        public Nullable<int> AGTYPUID { get; set; }
        public Nullable<int> PrimaryPBLCTUID { get; set; }
        public Nullable<int> SecondaryPBLCTUID { get; set; }
        public Nullable<int> TertiaryPBLCTUID { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<int> GroupUID { get; set; }
        public string GroupIsExcluded { get; set; }
        public int GroupDiscount { get; set; }
        public string GroupIsDiscountPerc { get; set; }
        public int GroupMaxCoverage { get; set; }
        public Nullable<int> SubGroupUID { get; set; }
        public string SubGroupIsExcluded { get; set; }
        public int SubGroupDiscount { get; set; }
        public Nullable<int> BillableItemUID { get; set; }
        public string BillableItemIsExcluded { get; set; }
        public int BillableItemDiscount { get; set; }
        public string BillableItemIsDiscountPerc { get; set; }
        public int BillableItemCoverage { get; set; }
        public string IsPackage { get; set; }
    }
}
