//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAllPayorAgreementsDiscount
    {
        public int AgreementUID { get; set; }
        public Nullable<int> AGTYPUID { get; set; }
        public Nullable<int> PrimaryPBLCTUID { get; set; }
        public Nullable<int> SecondaryPBLCTUID { get; set; }
        public Nullable<int> TertiaryPBLCTUID { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<int> GroupUID { get; set; }
        public Nullable<double> GroupDiscount { get; set; }
        public string GroupIsDiscountPerc { get; set; }
        public Nullable<int> SubGroupUID { get; set; }
        public Nullable<double> SubGroupDiscount { get; set; }
        public string SubGroupIsDiscountPerc { get; set; }
        public Nullable<long> BillableItemUID { get; set; }
        public Nullable<double> BillableItemDiscount { get; set; }
        public string BillableItemIsDiscountPerc { get; set; }
        public Nullable<int> GroupPBLCTUID { get; set; }
        public Nullable<int> SubGroupPBLCTUID { get; set; }
        public Nullable<int> ItemPBLCTUID { get; set; }
        public Nullable<int> GroupALLDIUID { get; set; }
        public Nullable<int> SubGroupALLDIUID { get; set; }
        public Nullable<int> ItemALLDIUID { get; set; }
        public Nullable<System.DateTime> GroupDateFrom { get; set; }
        public Nullable<System.DateTime> GroupDateTo { get; set; }
        public Nullable<System.DateTime> SubGroupDateFrom { get; set; }
        public Nullable<System.DateTime> SubGroupDateTo { get; set; }
        public Nullable<System.DateTime> ItemDateFrom { get; set; }
        public Nullable<System.DateTime> ItemDateTo { get; set; }
    }
}
