//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTech.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAllBillableItemRates
    {
        public int UID { get; set; }
        public Nullable<double> ItemAmount { get; set; }
        public Nullable<int> PBLCTUID { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<int> OwnerOrganisationUID { get; set; }
    }
}
