//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Authority { get; set; }
        public string ReferringPhysicianName { get; set; }
    }
}
