//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annotations
    {
        public int No { get; set; }
        public int ReferenceNo { get; set; }
        public string Data { get; set; }
        public string PatientID { get; set; }
        public string StudyInstanceUID { get; set; }
        public string SeriesInstanceUID { get; set; }
        public string SOPInstanceUID { get; set; }
        public string Writer { get; set; }
        public string ViewID { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public System.DateTime Created { get; set; }
    }
}
