//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institutions
    {
        public int No { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Logo { get; set; }
        public string Url { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
        public string Address { get; set; }
    }
}
