//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instances
    {
        public string SOPInstanceUID { get; set; }
        public string SeriesInstanceUID { get; set; }
        public string StudyInstanceUID { get; set; }
        public string SOPClassUID { get; set; }
        public string TransferSyntaxUID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string ReferringPhysicianName { get; set; }
        public string PerformingPhysicianName { get; set; }
        public string PatientComments { get; set; }
        public string PatientBirthDate { get; set; }
        public string PatientSex { get; set; }
        public string StudyDescription { get; set; }
        public string StudyID { get; set; }
        public string StudyDate { get; set; }
        public string StudyTime { get; set; }
        public string AccessionNumber { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<int> SeriesNumber { get; set; }
        public string SeriesDate { get; set; }
        public string SeriesTime { get; set; }
        public string SeriesDescription { get; set; }
        public string Modality { get; set; }
        public string BodypartExamined { get; set; }
        public Nullable<int> InstanceNumber { get; set; }
        public Nullable<int> NumberOfFrames { get; set; }
        public string PixelSpacing { get; set; }
        public string PixelAspectRatio { get; set; }
        public string SliceThickness { get; set; }
        public string SpacingBetweenSlices { get; set; }
        public string SliceLocation { get; set; }
        public string PatientOrientation { get; set; }
        public string ImagePositionPatient { get; set; }
        public string ImageOrientationPatient { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> RescaleIntercept { get; set; }
        public Nullable<double> RescaleSlope { get; set; }
        public string RescaleType { get; set; }
        public string WindowWidth { get; set; }
        public string WindowCenter { get; set; }
        public Nullable<int> SamplesPerPixel { get; set; }
        public Nullable<int> PlanarConfiguration { get; set; }
        public Nullable<int> BitsAllocated { get; set; }
        public Nullable<int> BitsStored { get; set; }
        public Nullable<int> HighBit { get; set; }
        public Nullable<int> PixelRepresentation { get; set; }
        public Nullable<int> PixelData { get; set; }
        public string AETitle { get; set; }
        public long FileSize { get; set; }
        public System.DateTime Created { get; set; }
        public string SpecificCharacterSet { get; set; }
        public string ImageType { get; set; }
        public string PhotometricInterpretation { get; set; }
        public string PatientAge { get; set; }
        public string LossyImageCompression { get; set; }
        public int Method { get; set; }
    }
}
