//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACS.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PACSEntities : DbContext
    {
        public PACSEntities()
            : base("name=PACSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Configs> Configs { get; set; }
        public virtual DbSet<Instances> Instances { get; set; }
        public virtual DbSet<Passwords> Passwords { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<SendSettings> SendSettings { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Studies> Studies { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
