//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientComments { get; set; }
        public string PatientBirthDate { get; set; }
        public string PatientSex { get; set; }
        public int NumberOfPatientRelatedStudies { get; set; }
        public int NumberOfPatientRelatedSeries { get; set; }
        public int NumberOfPatientRelatedInstances { get; set; }
        public string SpecificCharacterSet { get; set; }
        public System.DateTime Edited { get; set; }
    }
}
