//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studies
    {
        public string StudyInstanceUID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientComments { get; set; }
        public string PatientBirthDate { get; set; }
        public string PatientSex { get; set; }
        public string StudyDescription { get; set; }
        public string StudyID { get; set; }
        public string StudyDate { get; set; }
        public string StudyTime { get; set; }
        public string AccessionNumber { get; set; }
        public string InstitutionName { get; set; }
        public string ModalitiesInStudy { get; set; }
        public string BodyPartsInStudy { get; set; }
        public int NumberOfStudyRelatedSeries { get; set; }
        public int NumberOfStudyRelatedInstances { get; set; }
        public string SpecificCharacterSet { get; set; }
        public string PatientAge { get; set; }
        public System.DateTime Edited { get; set; }
        public int ReportStatus { get; set; }
    }
}
